### ISSUE TITLE
refactor file headers

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#115]
After various discussions it was determined that the correct headers should read something like 

```javascript
// Copyright (c) Microsoft Corporation and others. Made available under the MIT license.
// SPDX-License-Identifier: MIT
```
Where the actual named copyright holder is the first legal entity to create the file.
The key changes being
* remove "all rights reserved"
* proactively add "and others" rather than having this be some sort of thing to watch for in PRs etc.
* Add an explicit callout to the license rather than just referring to the SPDX identifier.

This issue will be open for a bit for comment/feedback but we need to move pretty quickly so we'll plan to do the change in a couple days barring compelling feedback to the contrary.

@kpfleming would love to get your explicit OK here

**Comment by kpfleming** [comment]
No objection from me. I prefer to see the explicit reference to the license in the text, in addition to the SPDX identifier.

**Comment by geneh** [comment]
service PR: https://github.com/clearlydefined/service/pull/118

**Comment by jeffmcaffer** [comment]
all done
