### ISSUE TITLE
Incorrect curation current result

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#116]
Repro steps:
https://dev.clearlydefined.io/curate
Look for npm/npmjs/-/chalk/2.3.1 or any package that was previously curated.
The current result contains `- 'curation/[object Object]'` in tools section.
![screen shot 2018-03-01 at 10 25 56 am](https://user-images.githubusercontent.com/1537662/36862205-fba34bb0-1d3a-11e8-91af-65c9055843f9.png)

**Comment by jeffmcaffer** [comment]
This is fixed
