### ISSUE TITLE
Add batch querying on definition endpoint

### ISSUE THREAD

**Issue by pxp928** [clearlydefined/service#1168]
Currently the definition end point requires you to query one at a time based on the coordinates. It would be much more efficient to be able to query in bulk. The bulk ingestion could take in an array of coordinates and return an array of responses based on those. 

For would be very helpful for services like GUAC (https://github.com/guacsec/guac/issues/1964) to be able to query clearlydefined endpoint and receive information back quickly without making multiple calls.

**Comment by qtomlinson** [comment]
@pxp928 Is https://api.clearlydefined.io/api-docs/#/definitions/post_definitions what you are looking for?

**Comment by pxp928** [comment]
Yes! I must have missed that. So would that have the rate limit of 250 /min?

**Comment by qtomlinson** [comment]
@pxp928 yes based on the [doc](https://docs.clearlydefined.io/docs/get-involved/using-data#production-instance-rate-limits).
