### ISSUE TITLE
PR "Details" webook link for curations is broken

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/service#121]
/curation vs /curate

**Comment by mynameistechno** [comment]
Sorry for being terse, it was just something I wanted to capture while testing another thing. The "Details" link in a PR, e.g. https://github.com/clearlydefined/curated-data-dev/pull/20 

Appears to be this line: https://github.com/clearlydefined/service/blob/master/providers/curation/github.js#L225 

Also, looks like the website hostname is hard coded (to dev.cd.io) in the URL that is posted to github. Is the hostname available in the config? If so, might as well update as part of this fix.

**Comment by jeffmcaffer** [comment]
ah, got it. The `endpoints.website` config prop should be the right thing to use as the base of the URL for details.

**Comment by mynameistechno** [comment]
@jeffmcaffer did you mean to close this? Doesn't look like the path was fixed from /curation to /curate yet.

**Comment by jeffmcaffer** [comment]
Nope. that was an error on my part. Sorry bout that
