### ISSUE TITLE
Support NuGet

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#128]
Now that the crawler supports NuGet, it should be supported in the service too.

**Comment by jeffmcaffer** [comment]
@geneh can you confirm that this is still an issue? I think the required support is there.

**Comment by geneh** [comment]
The following should be checked: https://github.com/clearlydefined/service/blob/5a7cf522f91c904addfb963348c9fc1f0d24d9e2/providers/summary/clearlydefined.js#L54
`// TOOD see if we can get the release date out of a nuget`

**Comment by fossygirl** [comment]
@Teju-Manchenella While you're doing the work on new package manager integrations, could you check this item and hopefully resolve the TODO and this issue?

**Comment by Teju-Manchenella** [comment]
Closed PR #154
