### ISSUE TITLE
Change to use copyright statement, not holder

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#161]
Initially we used the copyright holder (as defined by ScanCode) as the Attributions value in the ClearlyDefined definition. To better support scenarios like NOTICE file generation, we want to change to surface the copyright **statement** as discovered by the various tools. This should be a relatively simple change to `_collectAttributions` in `scancode.js`.

Should also look to see if there is anywhere else that summarizes attributions.

Having done this we will need to flush all existing definitions and either agressively recompute or let them lazily recompute.

**Comment by fossygirl** [comment]
Closing as #166 was merged.
