### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#165]
We need pervasive logging. We currently have AppInsights configured in that automatically gives request/response tracking with no code changes. If you don't supply a key then these are dumped to the console. In addition, there are higher value data that we can log related to particular requests as well as metrics, cache misses, and error cases. For that we do not want a direct dependency on AppInsights (maintain platform independence).

There are a couple of popular options

* Winston
* Bunyan

both of these work with AppInsights for storing the actual events so we can end up with all the data in one place. 

The crawler uses Winston already so unless someone feels strongly I suggest we also use that and the `winston-azure-application-insights` plugin.

**Comment by fossygirl** [comment]
@jeffmcaffer @dabutvin Just pinging this issue since I think we'd like to address this month to start to get more metrics to report on for ClearlyDefined.

**Comment by jeffmcaffer** [comment]
yup. it is in the October milestone. Chatted some with @AlexWebYourmind and friends about doing this work. we need to scope out what we want to do and then execute.

**Comment by moranthomas** [comment]
@jeffmcaffer - initial analysis indicates that crawler doesn't use winston (maybe ghcrawler does but it looks like it still calls morgan and console.log - https://github.com/Microsoft/ghcrawler/blob/develop/app.js). 
Do we have example code where it is using winston so I can keep usage consistent in both repos?
