### ISSUE TITLE
Should not persist definitions that are not found

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#183]
This is leaving unnecessary remnants in the production-definition container

### Steps to reproduce:

1. POST to https://api.clearlydefined.io/definitions
   ```
      [
          "npm/npmjs/-/co/9.9.999"
      ]
   ```
2. Get response

```
{
    "npm/npmjs/-/co/9.9.9999": {
        "described": {
            "tools": []
        },
        "coordinates": {
            "type": "npm",
            "provider": "npmjs",
            "namespace": null,
            "name": "co",
            "revision": "9.9.9999"
        },
        "score": 0
    }
}
```

### Expected:

No data to be persisted

### Actual:

Blob created at `npm/npmjs/-/co/revision/9.9.9999/tool/definition/1.json`

We should be able to return the same response we are returning right now, but not save any data to storage

**Comment by jeffmcaffer** [comment]
Addressed in #190
