### ISSUE TITLE
rate limiting on Azure Search

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#191]
I dropped a package-lock file listing many components that do not have precomputed definitions. This resulted in a number of 500 errors from the service. Looks like we were bombarding Azure Search adding the newly computed definitions to the to index.

Couple of things
1. we should not give a 500 back to the user. 
2. likely need to either batch up these adds (interestingly we were probably doing a batch of `gets` but the batchiness was being unwound further up. Not sure we can leverage that...
3. if we fail to add something to the index then users will not find it when they type in the filter bar on the site. Need some more fallback/robustness there. 
    * Consider queuing the indexing somehow. 
    * consider a period job that takes the latest new definitions and indexes them.
    * as a near term hack, recover from the 503 and retry a bit later. Still not robust in the face of crashes but might should be pretty easy to do.

{"error":{"code":"500","message":"Unknown\n503 - {\"@odata.context\":\"https://clearlydefined-prod.search.windows.net/indexes('coordinates')/$metadata#Collection(Microsoft.Azure.Search.V2017_11_11.IndexResult)\",\"value\":[{\"key\":\"bnBtL25wbWpzLy0vYXJyYXktZmxhdHRlbi8yLjEuMQ==\",\"status\":false,\"errorMessage\":\"Failed to execute indexing request for this document because not enough resources were available. You may be reaching the limits of your provisioned capacity. Please try again later or adjust the number of replicas. See http://aka.ms/azure-search-throttling for more information.\",\"statusCode\":503}]}","innererror":{}}}

**Comment by dabutvin** [comment]
this is not an issue anymore
