### ISSUE TITLE
Add initial PR job that will validate incoming curation patches

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/service#2]
When a PR is submitted with a curation patch to https://github.com/clearlydefined/curated-data:

- [x] Runs on Travis or CircleCI or equivalent
- [x] Job will validate curation patch yaml file
- [x] Correctly sets the status to success or error (Status ✅ )
- [x] Dump out the yaml in the log

**Comment by mynameistechno** [comment]
Consider putting any scripts in `.build` directory.

**Comment by mynameistechno** [comment]
For `curated-data` I'm leaning towards a folder structure similar to `DefinetlyTyped` - i.e. the types are housed in a `types` dir instead of at the root of the repo. That way it's name-spaced nicely and we don't have to worry about having folders such as `.build`. 

E.g. root dir 
- /scripts/  *(or build/)*
- /curations/ *(or w/e we want to call it)*
- .travis.yml
- package.json
- README.md

etc... 

Thoughts?

**Comment by iamwillbar** [comment]
That sounds reasonable to me.

**Comment by mynameistechno** [comment]
I will create follow up tickets as needed, the initial PR validation is in place.
