### ISSUE TITLE
Merged curation pull requests may not be actually augmenting the harvested data?

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#200]
We need to verify that this behavior is replicable, but we merged a pull request yesterday: https://github.com/clearlydefined/curated-data-dev/pull/182/files on dev data, and yet the component definition today remains the same: 
![screen shot 2018-08-16 at 1 37 57 pm](https://user-images.githubusercontent.com/17101092/44233783-a9ef6580-a159-11e8-950a-9da6cb2e0cc7.png)

Someone will need to go test this to make sure this isn't just very slow, actually working in prod and not in dev, or not replicable.

**Comment by fossygirl** [comment]
@jeffmcaffer I searched for async on dev.clearlydefined.io again today and it hasn't changed from the original definition. It seems to be disregarding your curation. Do you know that that might be?

**Comment by jeffmcaffer** [comment]
Interesting. I flushed the definition and now it is recomputed and has the curated values. 

So, it seems we are missing a webhook call from GitHub or have a bug in the processing of the webhook. Some thoughts:
* I checked the webhooks and the hook for PR 182 was successfully sent (see webhook d02106f0-a0aa-11e8-8720-1df4fb6eeb3d). That is a `pull_request` `closed` event.
* it is possible that we are getting the webhook and reading the repo (or associated info) too fast such that the GitHub db read replicas are not updated. Historically this has been a problem
* Also possible that the webhook code is just plain not working right

**Comment by jeffmcaffer** [comment]
This has been fixed. The issue was more architectural. The definitions were being computed based on a cached copy of the curation repo. Made sense for bulk computations but not for responding to the individual merge webhook calls. The net was the def was correctly being recomputed but it was using old curation data. All is good now.
