### ISSUE TITLE
Preview API returns duplicated attributions

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#203]
When a curation get posted to the preview API, some files returns back with duplicated attributions.

Take as example this definition: npm/npmjs/-/react-redux/5.0.7 which has a file with 4 attributions.

If the same definition, without any changes, passes through the preview API, it came back with 7 copyrights on the same file, some of them gets duplicated, as you can see in the attached screenshots.

<img width="602" alt="schermata 2018-08-20 alle 22 11 58" src="https://user-images.githubusercontent.com/7654979/44392783-4f784f80-a533-11e8-8fc1-5b2b862090b1.png">
<img width="771" alt="schermata 2018-08-20 alle 22 11 27" src="https://user-images.githubusercontent.com/7654979/44392784-5010e600-a533-11e8-9a6c-5cc584608519.png">

**Comment by jeffmcaffer** [comment]
This is addressed in #204. Please review. I suggest for unblocking the edit work, you use different components. This problem only happens where ScanCode see multiple instances of the same copyright in the same file. Seems like that should be rare?
