### ISSUE TITLE
Check status code of response when calling crawler

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#205]
at https://github.com/clearlydefined/service/blob/master/providers/harvest/crawler.js#L22

Right now we are returning the requestPromise in it's raw form. We should handle any non 2XX status codes and throw an exception from within the harvest provider.

While doing this work, we should take a quick scan of other usages of `requestPromise` and clean up all the invocations to handle non-success status codes

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer as per Weekly meeting discussion, any chance you or @dabutvin can modify this particular issue so that it's clear what the desired outcome is?   

@moranthomas do you have any followup questions?

**Comment by dabutvin** [comment]
replaced with https://github.com/clearlydefined/service/pull/365

We don't want to wrap everything in a try/catch/throw

We can throw exceptions naturally from the services and get stack traces in dev.
Specific status codes are handled in each route for things like bad request.
