### ISSUE TITLE
Implement the new scoring spec

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#225]
We now have a spec for the scoring algorithm (see https://docs.google.com/document/d/1o_VuVnP1PMoYOXZHSm0TyDX4CsqDXM3zqESAE0AoUnQ/edit#) and now need to implement it. The dual (tool and curated) scoring infrastructure is in place so now need to implement the actual score math.

**Comment by fossygirl** [comment]
@pombredanne I believe you alluded to being able to do this work for ClearlyDefined soon. Is that the case, and if so, do you have an update?
