### ISSUE TITLE
validate components in curations actually exist

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#227]
When a curation is PATCHed , the service should validate that the included components actually exist.
The service should also do this for curations submitted via the API so we can fail earlier for the user and prevent the bogus PRs from accumulating.

We should consider also doing this on PR webhook events since anyone can post a PR or change the files in a PR. In this case the service should mark the PR with an error "status" and point users to some page that guides them through the problem.

**Comment by moranthomas** [comment]
In order to create a curation PATCH you need to select a definition from the website. In this respect the component will have to already exist so this requirement is more specifically about calls directly to the API and validating components exist here in this case.
