### ISSUE TITLE
Handle components which have no license

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#237]
We currently only have a notion of a component missing a license. However, there are components that are not missing licenses, they in fact _have no license_. We should design and implement a way to support that in the component definition and display it to the user differently than missing licenses. 

We agreed it can't be "null" for other architectural reasons, so we'll need to find another solution for what the curator submits in the Declared License field and what's displayed to end users getting the definition for that component.

@dabutvin @jeffmcaffer for visibility.

**Comment by fossygirl** [comment]
We agreed we'd like to use the SPDX identifier `NONE` for these components.

**Comment by fossygirl** [comment]
@dabutvin @jeffmcaffer We have a component right now the curators believe is public domain:

nuget/nuget/-/SQLite/3.13.0

Do we want to curate this as `NOASSERTION` as well, or is this a new use case for handling things without a license?

**Comment by jeffmcaffer** [comment]
don't think we should ever use `NOASSERTION`. That is equivalent IMO to that value simply not being set. If you want to convey that we looked and did not find an open source license then `NONE` would be the right value

**Comment by moranthomas** [comment]
Hey @jeffmcaffer @fossygirl. Have you finalised your decision on this ? 
I'm unsure of what the ask is currently for the service layer

**Comment by fossygirl** [comment]
@jeffmcaffer I believe we agreed that for these cases we agree `NONE` is the intended curated SPDX expression?

@moranthomas We'll need `NONE` to appear as an option on the dropdown in the UI. Don't know if there are any service changes but I don't think so?

**Comment by jeffmcaffer** [comment]
After our discussion yesterday I think @fossygirl changed my mind. Here is where I *think* we ended up for license expression properties

* No value (actual property not present): there is no information about the license so far. typically this would be a tool that just can't find anything that it would associate with "licensing"
* NONE: it is confirmed that there is no license information of any kind. Unless the tools are omniscient, this will likely be a human curation.
* NOASSERTION: license information has been found but either can't be understood or cannot be expressed as an SPDX license expression. This could be used to capture commercial licenses as well as open source licenses that have been modified with special non-standard clauses

We should vet that these line up properly/plausibly with the SPDX meanings. @iamwillbar had some info and opinion on that. 

Assuming the above is the right direction, we'd need to ensure that NONE and NOASSERTION show up in the license picker

**Comment by iamwillbar** [comment]
I agree and it aligns with the SPDX meanings, however, if/when we generate a real SPDX document we would map no value to NOASSERTION because this field is required in SPDX and they don't differentiate between the 1st and 3rd bullets above.

**Comment by jeffmcaffer** [comment]
Sounds good. Let this be the plan of record and implement that.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer can you confirm that required changes to accomodate the agreed behaviour are only on the UI side of things?
If so, can we close this?

**Comment by moranthomas** [comment]
The options from the licence picker (on the UI side) are coming directly from here: https://github.com/shinnn/spdx-license-ids. So should we should create an issue on there to get these 2 options (NONE and NOASSERTION) added ?

**Comment by fossygirl** [comment]
@moranthomas Yes, please.

**Comment by fossygirl** [comment]
@moranthomas That's fine, but please also open an issue on us to add those options to our list in te meanwhile independent of what SPDX decides to do.

**Comment by AlexWebYourmind** [comment]
@fossygirl @jeffmcaffer does what mean we will no longer use the SPDX license picker to populate the options? 

Currently, the source picker is populated completely via SPDX data. 
Please see https://github.com/clearlydefined/website/blob/master/src/components/SpdxPicker.js


Do you want this code to be modified so that it includes also a private/separated list? Doable, as long as we avoid duplicates. 

@storrisi iI am nterested in hearing your thoughts as well.

**Comment by mynameistechno** [comment]
For now you can manually add those options to the array passed in to `SpdxPicker`. I've done this for an internal project where we wanted to add additional licenses not in SPDX:
```js
import spdxLicenseIds from 'spdx-license-ids'
import deprecatedSpdxLicenseIds from 'spdx-license-ids/deprecated'
const customLicenseIds = ['NONE', 'NOASSERTION']; // I'd put this in a config file
const identifiers = [...customLicenseIds, ...spdxLicenseIds, ...deprecatedSpdxLicenseIds]
```

**Comment by fossygirl** [comment]
Closing for https://github.com/clearlydefined/website/issues/342
