### ISSUE TITLE
Handle components which have a commercial license

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#240]
Some components will end up getting queued for harvesting that aren't open source, they are commercially licensed. We will have users who call ClearlyDefined about those components and will want to know that the components are commercially licensed. Just like components that have no license, we should specifically curate these components to say they are not open source and provide the commercial license they have instead.

**Comment by dabutvin** [comment]
There are a couple of SPDX concepts we could adopt here

When there is no license we can use the term `NONE`
https://spdx.org/rdf/terms/individuals/none___-1837002427.html

> When this value is used as the object of a property it indicates that the preparer of the SpdxDocument believes that there is no value for the property. This value should only be used if there is sufficient evidence to support this assertion.

Another one we can use is `NOASSERTION`
https://spdx.org/rdf/terms/individuals/noassertion___-960310162.html

> Indicates that the preparer of the SPDX document is not making any assertion regarding the value of this field.

Licensee uses `NONE` when the project is not licensed (e.g., all rights reserved)
and they use `NOASSERTION` when the project has a license, but they were not able to detect it

**Comment by fossygirl** [comment]
@dabutvin I like the idea of `NONE` for things that have no license. 

For things that are commercially licensed I think `NOASSERTION` is the wrong message; it's not that they didn't assert a license, it's that the license they assert isn't FOSS. I assume SPDX doesn't have an option for `COMMERCIAL` or something similar?

**Comment by dabutvin** [comment]
yeah i don't see anything about `COMMERCIAL`

If you put [this license](https://github.com/newrelic/node-native-metrics/blob/master/LICENSE) into licensee you get back `NOASSERTION` for what it's worth. I think that's a commercial license?

**Comment by iamwillbar** [comment]
From the SPDX spec here is how they define the license field, my issue with `NOASSERTION` is it covers three different scenarios that might be interesting to differentiate, specifically differentiating "we looked and found a license but we don't recognize what license it is" versus "we looked and didn't find a license" seems like a useful distinction. 

We could extend the spec to add `UNKNOWN` (I think `COMMERCIAL` implies a level of confidence that it's a commercial license that we just don't have) which would replace `NOASSERTION` for case (i) and we would use `NOASSERTION` only for case (ii) and (iii). I don't like mixing and matching the spec like this but the distinction feels important.

```
The options to populate this field are limited to:
* A valid SPDX License Expression as defined in Appendix IV;
* NONE, if the SPDX file creator concludes there is no license available for this package; or
* NOASSERTION if:
(i) the SPDX file creator has attempted to but cannot reach a reasonable objective determination;
(ii) the SPDX file creator has made no attempt to determine this field; or
(iii) the SPDX file creator has intentionally provided no information (no meaning should be implied
by doing so).
```

**Comment by jeffmcaffer** [comment]
ClearlyDefined is about open source and the license properties are specifically about open source (well SPDX) licenses. So effectively we are saying that you either have an SPDX recognized license or you don't have a license (i.e., NONE). Seems alright to me. Users looking for commerical things SHOULD actually not get any info.  IMHO it is an error if they get anything from the system.

It seems unlikely that we'll be able to confidently detect that a component has a license but that we don't know it. Most of the tools work by matching known licenses to given text. By definition then, if the tool does not know the license it will not recognize it as a license. It's just a file called LICENSE that could say anything in it. It would be quite advanced (and IMHO needlessly) to have a tool that could take random text and infer that it was some kind of license.

As for using NOASSERTION, I'd rather just leave the value out.  reasoning matching your numbering

i) not sure it matters that someone tried
ii) didn't try. we'll that would be every empty value in the definition prior to curation
iii) the parenthetical indicates that that value has no meaning.  just leave it out.

**Comment by iamwillbar** [comment]
I think we need to be able to programmatically differentiate:
* License not harvested
* Did not find any license information
* Found license information but it's not an open source license
* Found license information and it is a recognized open source license

The reason for this is the workflow we'll undertake is different in each case:
* Request it to be harvested
* Request the project to add a license
* Treat the project as not open source and follow our non-open source workflows
* Treat the project as open source and follow our open source workflows

Also, if a curator has gone to the effort to investigate the project and works out that it's not an open source project it seems a shame to lose that information. We don't need to categorize it or identify the license in anyway, just capture that yes there is a license.

**Comment by jeffmcaffer** [comment]
1) we can tell if there are any "tools" involved in the definition. If none, we did not harvest. That is not specific to licenses
2) a missing value in the property should indicate that we did not find anything
3) Not sure how we know we found a license if it is not something we recognize as a license. A LICENSE file is a good hint but not conclusive. 
4) SPDX id

For #3 it seems like we can use NONE to capture that. For example, if we think of the "license" fields as really being "open source license", then saying there is NONE means that either we looked and could not find one or we've not looked. #1 can help users distinguish.

**Comment by jeffmcaffer** [comment]
Can this issue be closed now? Summary being a given license property is 
* empty (non-existent) if tools did not find anything
* NONE if someone looked and did NOT find something that could be interpreted as or converted to an SPDX expression
* an SPDX license expression if something was found or curated in

If so, 
* I think this is already covered in the code. @dabutvin may have different info.
* @fossygirl this should go in the curation doc for what to do when they find this case

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer it appears that your answer above covers also #237  in some way?

**Comment by fossygirl** [comment]
@AlexWebYourmind @jeffmcaffer and I discussed this a little in person yesterday. It sounds like we are considering `NOASSERTION` for commercial licenses, but we didn't resolve this so I'm leaving this open for now.

**Comment by fossygirl** [comment]
Closing for https://github.com/clearlydefined/website/issues/342
