### ISSUE TITLE
Checking a curations returns a read "getCurationUrl" of undefined error

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#250]
When posting a contribution, if you go the website URL to check the curation, like [this](https://dev.clearlydefined.io/curations/185), the API called returns `Unknown Cannot read property 'getCurationUrl' of undefined`

Full message [here](https://dev-api.clearlydefined.io/curations/pr/185)

**Comment by dabutvin** [comment]
@jeffmcaffer fyi.

I think we tried to fix this with https://github.com/clearlydefined/service/commit/6ccb00d5d8abe1b11afce0163234437368932258

but there is something else wrong

**Comment by jeffmcaffer** [comment]
That was the same problem but in another place/route. we were using `this` when there is no object. Fixed in https://github.com/clearlydefined/service/commit/507da5dfa345feda7f683ad35df22068a1c3dfc0 that I just pushed to master
