### ISSUE TITLE
validate the id of the committer in curation PRs

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#252]
ideally the committer tracked in PRs would be the user who did the contribution rather than the clearlydefinedbot. We attempt to use the user's info but fall back if we can't find it. However, I was logged in and the service should have been able to identify me and my email etc yet my contribution commits appeared to come from clearlydefinedbot

**Comment by dabutvin** [comment]
let's make the commiter the logged in user, if they are logged in

you can set the commiter with the contents api https://developer.github.com/v3/repos/contents/#example-input
