### ISSUE TITLE
Add PRs to the doc db

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#253]
Now that we have document db support, add a mechanisms for 
* storing PR related data (e.g., the PR itself)
* updating the PRs as they change
* querying to find the set of components affected, open/close/merged state of the PR, people related to the PR, ...

**Comment by moranthomas** [comment]
Hey @jeffmcaffer - just checking if this needs to be handled by us or is it being addressed by your side ?

**Comment by jeffmcaffer** [comment]
There is a WIP PR # 256 that covers this. Making reasonable progress but keep being in places that have crappy internet so it's hard to experiement against actual azure.
