### ISSUE TITLE
API error for heavy definitions

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#254]
If you are checking for a very large definition, like: https://dev.clearlydefined.io/share/eJwty0EOgyAQheG7zNqFlqrIstdoXADOtJMoYwBNjPHuxaTL9+X9JxDPGSOY86ogScyvA0zY5rkCLxInDjZjAvM+IR8rgoEPZ6hgjbLzdIc3fDdXLNgF02r9/VrYR0lC+e+F9uRlwrIj7pxYQrHnUCP1XeP6zilSTmn1QKLetlpb6/XQYEuoa7jG6wfYiziO

 while getting the data the /definitions API returns an error: `Request size is too large`

**Comment by dabutvin** [comment]
Got another repro of this

Getting this error calling out to https://api.clearlydefined.io/definitions

```json
[
    "git/github/jersey/jersey/79e9d1350c86c56842c710f26760521cfc621d91"
]
```

```json
{
  "Errors":[
    "Request size is too large"
    ]
}
ActivityId: 5ca3aba1-0000-0000-0000-000000000000
Request URI: /apps/c34c877c-82a9-4ed6-8bd3-f16f6362f81a/services/14322c7c-abda-46cc-9a15-7ff1ba59f8e4/partitions/f4263426-8da6-4603-9dc6-79daf176079f/replicas/131838436397201159p,
RequestStats: 
RequestStartTime: 2018-10-23T17:21:23.3073595Z, Number of regions attempted: 1
, SDK: Microsoft.Azure.Documents.Common/2.0.0.0
```

There's a limit in place on our definition store at 2MB inserts

The scancode output alone for this component is 13.3MB

**Comment by moranthomas** [comment]
Do we have a figure in mind as to what size we should set the upper limit to?
This may be a limit on the azure side.... 
Should we be breaking up the request into smaller chunks and sending individually?

**Comment by dabutvin** [comment]
It is a limit on the azure side.
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-resources#documents

The maximum size of a document is 2MB

I think as a first step, we need to investigate why exactly these definitions are growing to be bigger than 2MB

**Comment by jeffmcaffer** [comment]
Yeah, there would have to be a boat load of files to have a 2MB json file for the **definition**. The scancode output goes into blob so is not subject to this limitation. Not as well that I belive we are storing the docs nicely formatted. We could change to no formatting and likely get quite a size reduction.

**Comment by dabutvin** [comment]
from https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/19164487-compress-stored-data

> We’re evaluating more compressed storage formats. Meanwhile, please consider using a client-side compression library for encoding fields/JSON fragments that are not used for querying.

**Comment by jeffmcaffer** [comment]
Oh that feels harsh in this context. we don't really know what data fields will be queried (and indeed we want to be able to query them all, that's why we are using a docdb). We should be able to a one line change to the JSON.stringify call no? or is it the CosmosDB client that is doing the stringify?

**Comment by dabutvin** [comment]
I can't tell from the docs. 

Looking at a computed definition for the affected component, it's got about 4000 files listed in it.

What do you think about compressing just the files property of a defiintion?

![image](https://user-images.githubusercontent.com/5168796/47536604-e46e3080-d875-11e8-997a-1411c561ebf2.png)

**Comment by jeffmcaffer** [comment]
Would rather not as that means we are making assumptions about what kind of queries we'll want to do. I could totally see someone wanting to query for all files with a certain license or copyright holder. 4000 files is a lot but not unreasonable. I wonder if we can make the file entries smaller. Are there elements there that can be deleted or inferred or ...

**Comment by dabutvin** [comment]
It looks like this
![image](https://user-images.githubusercontent.com/5168796/47621736-6b5f1b00-dab9-11e8-82ec-3f0a5d9e54bf.png)

We could think about storing the data a little differently to not repeat ourselves over and over again, would make the queries more complicated, but could still be done.

something like

```json
"files": {
  "attributions": {
      "1": "Copyright (c) 1989, 1991 Free Software Foundation, Inc.",
      "2": "copyrighted by the Free Software Foundation",
      ...
  },
  "licenses": {
      "1": "CDDL-1.1 and GPL-2.0",
      "2": "CDDL-1.1",
      ...
  },
 "paths": [
    {
       "path": "bundles/repackaged/jersey-jsr166e/pom.xml",
       "attributions": ["1", "2"],
       "license": "1"
    },
    {
       "path": "archetypes/jersey-heroku-webapp/pom.xml",
       "attributions": ["2"]
    },
    ...
  ]
```

**Comment by dabutvin** [comment]
maybe another idea to explore is some kind of document splitting

**Comment by dabutvin** [comment]
we're starting to get more and more of these.

Here are some that popped up today

```
git/github/apple/turicreate/e4aad253af795b8364fc6602e4772a1ee1dcf0f7 |  
git/github/aws/aws-sdk-cpp/416ccea8067c80c2fab472b39f1dd3cea756be1e |  
git/github/aws/aws-sdk-net/326ae01e1f6a8809717e80ec584b819fcad22a4c |  
git/github/castleproject/core/c849552fa57e2945f06022ae64fff3ebe8313124 |  
git/github/crytek/cryengine/ba1b181d5559ea23d84467c9a1f684214dcbdf52 |  
git/github/directproject/nhin-d/bb8588a00e17e954aeeaa5119b706ac904c9d10f |  
git/github/dotnet/coreclr/a536e7eec55c538c94639cefe295aa672996bf9b |  
git/github/gradle/gradle/efa19eab32c77ae8c0f3f9a02c0ae47444cc05d7 |  
git/github/microsoft/codecontracts/bf32538c8be7ad22aee546b8762252abb92b97a2 |  
git/github/microsoft/referencesource/4fe4349175f4c5091d972a7e56ea12012f1e7170 |  
git/github/microsoft/winobjc/35ec6b12c5980f9badf860f740ba2af84b3d87aa |  
git/github/microsoft/winobjc/a3c7ddfa8bd6cb362e738064971dc4f9ace6164c |  
git/github/mono/monodevelop/a2163670efe259c85cd8f335d95b175068fbbe2a |  
git/github/mono/monodevelop/ac9b7fcba9ee92ac30c8eb90f20c2228ce033efa |  
git/github/odata/odata.net/0fef8e29a3a3182dc0d0774fbfc79d1f53160f5e |  
git/github/rethinkdb/rethinkdb/8aa356f85287ec946b014a8e056799f143e65178 |  
git/github/rethinkdb/rethinkdb/8aa356f85287ec946b014a8e056799f143e65178?expand=prs |  
git/github/runtimejs/runtime/0af7ab420475a63e5aa1758dac371140f2231ce1 |  
git/github/runtimejs/runtime/22a16171c627eee476cde48d703ab5fc450b9331 |  
git/github/tokutek/mongo/caf60eb5d8f705dd100b6d01537fab260e8c4bc9

```

Thinking about how this would improve if we changed the structure to

```
"files": {
  "attributions": {
    "Copyright 1": [ "path1", "path2"],
    "Copyright 2": [ "path2"]
  },
  "licenses": {
      "CDDL-1.1 and GPL-2.0": ["path1", "path2"],
      "CDDL-1.1": ["path1", "path2"]
  }
}
```

**Comment by dabutvin** [comment]
let's try out the indexing option https://github.com/clearlydefined/service/issues/254#issuecomment-433741270

**Comment by dabutvin** [comment]
The indexing is not good enough, these documents will still be greater than 2MB.

Even gzipping the entire document in some cases exceeds the 2MB limit.

I think the next step to try is paginating files for a single definition across documents.

**Comment by dabutvin** [comment]
the fix for this is now in production. We are paginating the files property across documents in chunks of 1000. This is internal to the mongo store and totally transparent for callers of the definitionService
