### ISSUE TITLE
Change curation title generation

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#259]
The title that's currently getting created for PRs doesn't really give the user at a glance any real information about the component in question or the curation. We should make the titles more informative and useful.

![46692392-fe441e00-cbbb-11e8-8588-eb95f885d743](https://user-images.githubusercontent.com/17101092/47390337-fad88880-d6cb-11e8-9d54-9aaaf84845af.png)

**Comment by dabutvin** [comment]
here's an example of using the subject line: https://github.com/clearlydefined/curated-data-dev/pull/387
