### ISSUE TITLE
Provide DocDb backend implementation for Apply Related Curations

### ISSUE THREAD

**Issue by moranthomas** [clearlydefined/service#260]
This is an extension of issue #291 - Apply related curations -  https://github.com/clearlydefined/website/issues/291 

Here the issue is that it often happens that one curation can apply to multiple components. For example, a missing license on v1.0 might be applicable to v1.1, 1.2, 2.0, ... We do not want to automate that but we should make it very easy to apply an existing curation to related components. Consider pulling in non-curated data as well. 

The website side of this has been implemented already but requires real data now to be supplied from the API on the backend

**Comment by jeffmcaffer** [comment]
Great point @moranthomas. We should define the set of interesting relationships (e.g., version to version, package to source, ...) and the develop the appropriate queries.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer Correct. from our standpoint, we will extend the descriptions issue adding information on the required APIs/Data. @moranthomas  will then implement those, unless already available. This includes building appropriate queries as per your comment above.

**Comment by storrisi** [comment]
This a sample of a potentially change of the schema of a definition that could be returned by the implementation:

```
"licensed": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "score": { "$ref": "#/definitions/score" },
        "toolScore": { "$ref": "#/definitions/toolScore" },
        "declared": { "$ref": "#/definitions/declared" },
        "facets": { "$ref": "#/definitions/facets" },
        "suggestions": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "declared": { "$ref": "#/definitions/suggestions" },
            "facets": { "$ref": "#/definitions/suggestions" }
          }
        }
      }
    },
```

```
"definitions": {
    "suggestions": {
      "type": "array",
      "items": { "$ref": "#/definitions/suggestion" }
    },
    "suggestion": {
      "type": "object",
      "properties": {
        "versions": {
          "type": "string",
          "description": "The version related to the value"
        },
        "value": {
          "type": "string",
          "description": "The value contained in the version"
        }
      }
    },
```

We could end up using this schema, and returning these data when the api is called with `expanded=suggestions`
or build a separate API which only return the suggestions, using a quite similar structure.

Thoughts?
