### ISSUE TITLE
Ignoring file and folders not interesting

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#264]
As mentioned in https://github.com/clearlydefined/website/issues/319, there is a problem of "ignoring" files/folders we know to not to be interesting. 

The .git folder is one example.

**Comment by jeffmcaffer** [comment]
I actually think that this is a crawler issue. We should not be scanning .git folders (etc) and storing data for them Just a waste.

**Comment by dabutvin** [comment]
this has been fixed
