### ISSUE TITLE
Origins API contains duplicate revisions 

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#265]
In some cases, the list of the returned revisions contains duplicates, like https://dev-api.clearlydefined.io/origins/rubygems/thread_safe/revisions

**Comment by AlexWebYourmind** [comment]
Bringing this in November scope as it's still an issue, @jeffmcaffer @dabutvin @moranthomas   .

**Comment by jeffmcaffer** [comment]
Interesting. I did not see this. We are returning exactly what we get from the repository. Would be easy enough to dedupe. See line 25 in originRubyGems.js
