### ISSUE TITLE
Create a new browse API

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#324]
This endpoint should be used from the new Browse Page implemented on the UI.
It should return a list of definitions, that a curator can use to contribute.
The API should accept the provider as a param, and return a list of some definitions with score < 70, sorted by default by lowest score first.

I'm opening this issue to address all the requirements and questions that we need to build the endpoint:
- how many definitions should we list?
- is the list totally random?
- are there already some methods that we can use to query the db for this specific behavior?

**Comment by dabutvin** [comment]
We will need to add a method in the mongo store that accepts a query object.maybe add a parameter to https://github.com/clearlydefined/service/blob/master/providers/stores/mongo.js#L35-L41
However, we should make sure not to expose a query parameter in a route as an API as it could expose an unwanted attack surface.

We could start with extending the definitions route like:

```
https://api.clearlydefined.io/definitions/?type=npm&page=2&sort=license
```

Here's my proposed answers to your questions

 - list 50 defintions per page
 - start with returning the results given and we can refine next iteration
 - something like `db.getCollection('definitions').find({ 'coordinates.type': 'npm' }).sort({ 'licensed.score.total': 1 })`

**Comment by jeffmcaffer** [comment]
Browse for things to curate is one usecase. For an API on the service we are really doing more like [GitHub Issue API](https://developer.github.com/v3/issues/#list-issues-for-a-repository). Essentially a set of params that we then translate directly into a query (after validating). I like the direction that @dabutvin suggests with just augmenting /definitions with query params. Nice and RESTful.

We can start simple and support just a few params but eventually I suspect this will become quite rich.

**Comment by storrisi** [comment]
I'm closing this since the Browse Page has been built using the new `/find `API
