### ISSUE TITLE
API returns 500 on maven coordinates

### ISSUE THREAD

**Issue by arnom-ms** [clearlydefined/service#346]
The behavior seems to be unique to some components only for example:
POST of 
`[
"maven/mavencentral/avalon-framework/avalon-framework/4.1.5"
]`

to https://api.clearlydefined.io/definitions

returns 
`{
    "error": {
        "code": "500",
        "message": "Unknown\nCannot read property 'map' of undefined",
        "innererror": {}
    }
}`

Same with :   
     "maven/mavencentral/logkit/logkit/1.0.1"
     "maven/mavencentral/javax.servlet/servlet-api/2.3",
     "maven/mavencentral/org.docbook/docbook-xml/4.4",
     "maven/mavencentral/org.apache.ant/ant-nodeps/1.8.1",

**Comment by dabutvin** [comment]
fixed in #351
