### ISSUE TITLE
Add copyright attribution to data model

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#362]
Need a way to build in the definition the ability to curate copyright attribution.

**Comment by dabutvin** [comment]
do we want to put copyrights on things that are not files?

**Comment by jeffmcaffer** [comment]
The only other thing would be the component itself. Not sure that it can or does have a copyright. @fossygirl do you remember the scenario here?

**Comment by fossygirl** [comment]
@jeffmcaffer I don't actually know what the specific use case would be here. I think we may want to just close this and see if the curators need it.
