### ISSUE TITLE
Add schema validate to curations

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#39]
Validate schema

* of proposed curation when a PR is opened/modified (e.g,. the status check)
* of the resultant summary after applying the proposal (also in the status check)
* in the web ui (separate issue for that)

**Comment by mynameistechno** [comment]
This is mostly completed in #52

**Comment by fossygirl** [comment]
@mynameistechno How are things going with this? We'd like to drive toward having this in the demo.

**Comment by mynameistechno** [comment]
Yeah this was completed to my knowledge. There will be tweaks to the schema, but the system and check is in place.
