### ISSUE TITLE
Define schemas for all the forms of data

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#40]
* curations (single revision browser form, full revision list PR form)
* summary documents
* REST end points

**Comment by mynameistechno** [comment]
In #52 I added a schema for curations.

**Comment by jeffmcaffer** [comment]
Really need to figure out the schema referencing and validation story.

**Comment by dabutvin** [comment]
we have https://github.com/clearlydefined/service/tree/master/schemas now
