### ISSUE TITLE
npm for ClearlyDefined Notice files

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#400]
@dabutvin let me know if you need any more context on this.

Would be great to have a ClearlyDefined npm that folks can put in their build and get NOTICE files out of.

**Comment by fossygirl** [comment]
Also want an npm that does web requests.

**Comment by fossygirl** [comment]
@iamwillbar

**Comment by jeffmendoza** [comment]
@notlaforge did this: https://github.com/clearlydefined/noticeme
