### ISSUE TITLE
Add new described/urls section to the definition

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#403]
We want to surface a set of URLs in the definition themselves, to be computed by the service.

for github:

```json
{
  "described": {
      "urls": {
           "homepage": "https://github.com/clearlydefined/service",
           "component": "https://github.com/clearlydefined/service/tree/9f6f79a17460c92fb3876d9f485411d43aa70374",
           "download": "https://github.com/clearlydefined/service/archive/9f6f79a17460c92fb3876d9f485411d43aa70374.zip"
       }
  }
}
```

for npm:

```json
{
  "described": {
      "urls": {
           "homepage": "https://www.npmjs.com/package/tiny-attribution-generator",
           "component": "https://www.npmjs.com/package/tiny-attribution-generator/v/0.0.6",
           "download": "https://registry.npmjs.com/tiny-attribution-generator/tiny-attribution-generator-0.0.6.tgz"
       }
  }
}

**Comment by dabutvin** [comment]
- [ ] add support for each provider
 - [ ] bump definition schema version
 - [ ] update definition schema validation

**Comment by pombredanne** [comment]
@dabutvin It would be great to use the most explicit name for each attributes
`homepage` and `download` are fine. `component` is less so, it is some kind of "package manager homepage" of sorts.

**Comment by dabutvin** [comment]
implementation guidance
---

 In [definitionService/finalizeDefinition](https://github.com/clearlydefined/service/blob/master/business/definitionService.js#L275-L280) add `_ensureUrls()` method

similar to `_ensureSourceLocation`, we will create the described.urls section
