### ISSUE TITLE
Return curations list when calling curations with ?expanded=prs param

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#408]
As mentioned in [this document](https://docs.google.com/document/d/1pB5ue8It7mRO1K4tesLGMTXcbZWVg7Q8N0ibTIft1fA/edit#) wrote by @jeffmcaffer , the response schema when calling the curations API with the `?expanded=prs param` should be:

```
“_meta”: {
    "schema": "1.1.0",
    "pending": [
      { 
        "number": 23,
        "title":  "some more cool changes",
        "contributor": "jeffmcaffer"
      }      
    ],     
    "merged": [
      { 
        "number": 3,
        "title":  "some cool changes",
        "contributor": "jeffmcaffer",
        "curator": "willbar"
      }      
    ]

```

**Comment by jeffmcaffer** [comment]
Please don't feel bound to that spec. It was a) just a stab in the dark and b) done some time ago.

**Comment by storrisi** [comment]
This has been done in #412 , so probably we could close this one

**Comment by dabutvin** [comment]
👍
