### ISSUE TITLE
Move URL computation to ClearlyDefined summarizer

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#419]
in #410 we added various URLs for each definition. Given that that code is necessarily provider-specific, it would be good to isolate it with the other provider-specific code that is in the ClearlyDefined summarizer (https://github.com/clearlydefined/service/blob/master/providers/summary/clearlydefined.js). 

In the eventual future all of the provider-specific code will be factored out into separate modules for each provider do lumping it all together is a good deal. 

Related, it is likely that the PyPi data needed to get or construct the download URL is already available in the harvested data that is made available to the summarizer. So rather than calling pypi to get the URL, we should be able to access it from the existing data.

**Comment by storrisi** [comment]
> Related, it is likely that the PyPi data needed to get or construct the download URL is already available in the harvested data that is made available to the summarizer. So rather than calling pypi to get the URL, we should be able to access it from the existing data.

Thanks! This is a great hint.
I will try to modify that method following this suggestion.
It could be helpful to have some kind of guideline, has @dabutvin did for guiding me to build the `ensureUrls()` method.

**Comment by jeffmcaffer** [comment]
`clearlydefined.js` has separate methods for adding provider-specific data (e.g., `addNpmData`). The suggestion here is to spread the recently added code over those methods. So `addNpmData` would add in the URLs specific to NPM. For PyPi, the `data` argument to `addPyPiData` is all of the content coming from the crawler/harvester. The thinking is that that may/should/could have the URL you need so rather than calling out to PyPi, we can pull the value from there.

**Comment by storrisi** [comment]
Thanks @jeffmcaffer , i will work on that.
