### ISSUE TITLE
API key and rate limiting design

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#42]
Need something simple.

Consider CloudFlare as we are already using their infrastructure to front for *clearlydefined.io. @jpeddicord suggests using one of the express rate limiter middlewares. That might be easier to manage at least in the first instance.

**Comment by jpeddicord** [comment]
Taking a peek at this now -- I think we can do this in a simple manner and scale up later.

**Comment by fossygirl** [comment]
@jpeddicord I believe you got through this with [#109](https://github.com/clearlydefined/service/pull/109). Anything left to do here, or can we close?

**Comment by jpeddicord** [comment]
No more action items; I'm just bad at paying attention to open issues. 😅
