### ISSUE TITLE
Ensure GitHub is not called during definition recompute

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#422]
It seems like GitHub is being called somewhere in the process of recomputing a definition. We had a case just now where the GitHub tokens were exhausted. At the same time, we were able to load new definitions (from the definition store) but older definitions needed to be recomputed and that caused a 500 to be returned.

All data that goes into a definition should be gathered via the crawlers. This makes the definition recomputable from just the static data. Things like suggestions and curations can access GitHub (whatever) but /definitions should be just the harvested data.

**Comment by dabutvin** [comment]
this is done
