### ISSUE TITLE
definition name queries are too slow

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#429]
Example: http://api.clearlydefined.io/definitions/?name=nlog

We are searching with regex on the mongo db and it is too slow now that it is fully populated.
When you run regex in the query it cannot leverage the index and is basically unusable.

Indexed queries are fast, for example, https://api.clearlydefined.io/definitions/?provider=npmjs

This shows up in the textbox on /browse

**Comment by dabutvin** [comment]
We may want to leverage the search index in this case for a 'full text' style search to get better results.

**Comment by jeffmcaffer** [comment]
Sounds interesting. So internally we would use the search to get a set of candidates, then call the DB to get the contents? How would this work for paging?

**Comment by dabutvin** [comment]
I think best case we would use a single store for the query.

we could see about using https://docs.mongodb.com/manual/core/index-text/#index-feature-text

**Comment by dabutvin** [comment]
turns out that is not supported by our db provider :(
https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/19762804-add-support-for-search-text-text-operator

They suggest using search indexing side by side for this functionality.

I've opened #431 to remove the regex support, we should make updates on the website side to make this more usable without partial matches

**Comment by dabutvin** [comment]
closing this for now as we have worked around the issue.
We can revisit if we need to do full text search
