### ISSUE TITLE
Improve find definitions with effective and tools score

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#436]
As mentioned in https://github.com/clearlydefined/website/issues/495 , we want to be able to search definitions that have a specific effective and tools score value.

To do that, the mongoDb query could be possibly be improved in order to search on the average value between licensed.score and described.score (effective score) and licensed.toolScore and described.toolScore (tools score).

@dabutvin @jeffmcaffer @pombredanne thoughts?

**Comment by dabutvin** [comment]
Here is a proposed definition schema adding the `score` property

```
{
  "described" : { ... }
  "licensed" : { ... }
  "_meta" : { ... }
  "score": {
     "tool": 88,
     "effective": 95
}
```

```
score.tool = avg(described.toolScore.total, licensed.toolScore.total)
```

```
score.effective = avg(described.score.total, licensed.score.total)
```

**Comment by jeffmcaffer** [comment]
addressed in #439 with a slight deviation from the spec above. `scores` rather than `score` and `curated` rather than `effective.

```json
{
  "described" : { ... }
  "licensed" : { ... }
  "_meta" : { ... }
  "scores": {
     "tool": 88,
     "curated": 95
}
```

**Comment by dabutvin** [comment]
Would we still use curated if it was never curated when tool matches?

**Comment by jeffmcaffer** [comment]
Hmm, we would always use the "curated" score but your scenario makes me think that the name is bad as it implies that it was curated. `effective` has the benefit of being just that, the effective score after applying any curations. If there are none, well, ok, there are none. I'll change it back.
