### ISSUE TITLE
add support for python zip files for download urls

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#445]
see https://pypi.org/pypi/azure-mgmt-rdbms/json as an example

it is not a `.gz` it is a `.zip` so it doesn't get picked up

see https://github.com/clearlydefined/service/blob/master/providers/summary/clearlydefined.js#L286-L297

**Comment by storrisi** [comment]
Maybe adding a condition to check if the extension is ".zip" or ".tar.gz" could work.

I actually don't know how many kind of extensions could have a pypi download package.
