### ISSUE TITLE
[Suggestions] Include 'discovered' licenses for declared license suggestions

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#453]
This would only show up if the declared license was missing or 'NOASSERTION' and there was a discovered license available within this definition.

A simple case for example:
package.json contains `"license": "BSD"` which is not SPDX parseable, but the package contains a LICENSE file that is detected as the `BSD-3-Clause` license, we can suggest `BSD-3-Clause` as the declared license

**Comment by dabutvin** [comment]
@storrisi how's it going here?

**Comment by ignacionr** [comment]
@dabutvin @storrisi I will be taking as an example the definition at https://api.clearlydefined.io/definitions/gem/rubygems/-/autobuild/1.6.2.b8 ; it has a declared 'NOASSERTION' but discovered 'GPL-2.0' from README.txt. Kindly let me know if you find that's not a fit example.
