### ISSUE TITLE
Ruby OR (NOASSERTION OR NOASSERTION) shouldn't be possible

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#461]
This is probably a problem with our join on Declared license?

![Screen Shot 2019-03-28 at 4 24 02 PM (2)](https://user-images.githubusercontent.com/17101092/55199193-70162100-5176-11e9-8146-425d67225833.png)

**Comment by pombredanne** [comment]
This sounds like a bug to me https://clearlydefined.io/definitions/gem/rubygems/-/prawn-table/0.2.2

**Comment by dabutvin** [comment]
let's see if this is fixed with #498 will have to recompute to check.
If it is, we should proactively clean up

**Comment by dabutvin** [comment]
It does not look like this was the issue here - needs further investigation

**Comment by storrisi** [comment]
We can investigate on this. Anyone does know what should be the right License, in order to check what's going on?

**Comment by ignacionr** [comment]
@storrisi that and a few other products of expanding and simplifying were already in place. But as discussed during the meeting, we will also remove the code that forces an overwrite of NOASSERTION when combined with any value (which makes the code of the tests start with data that isn't viable).

**Comment by fossygirl** [comment]
@ignacionr Did you follow up on this and did we get it resolved?

**Comment by ignacionr** [comment]
This issue was commented on https://github.com/clearlydefined/spdx/pull/1 and decided to close as is.

**Comment by fossygirl** [comment]
Reopening and confirming this is still a problem. GPL OR NOASSERTION shouldn't be possible. 
![Screen Shot 2019-09-09 at 2 42 10 PM](https://user-images.githubusercontent.com/17101092/64568734-59bce580-d310-11e9-94f6-9396f7ca3578.png)

**Comment by nellshamrell** [comment]
I have not been able to reproduce this. If anyone else sees this in their work, please feel free to re-open this issue.
