### ISSUE TITLE
Sort by highest score doesn't produce an ordered descending list

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#464]
As mentioned in https://github.com/clearlydefined/website/issues/637 sorting for High Scores produces some wrong results.

See ![Screen Shot 2019-03-28 at 4 07 52 PM (2)](https://user-images.githubusercontent.com/17101092/55198595-d5b4de00-5173-11e9-86d2-65cfe2c512a6.png)

**Comment by jeffmendoza** [comment]
Still happening.

Don't know if this should be a service issue, or if the website should be joining and re-sorting service responses.

**Comment by nellshamrell** [comment]
This appears to now be working as expected:

![image](https://user-images.githubusercontent.com/813007/103941591-f0a3d880-50e3-11eb-9711-3d7fc3510902.png)
