### ISSUE TITLE
Unknown scancode 3.2.2 version reported

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/service#481]
There seem to be a discrepancy there: the latest version of ScanCode is 3.0.2

I can see `Tools clearlydefined/1.3.3, licensee/9.12.1, scancode/3.2.2, fossology/3.6.0` in the UI 
and in the definition and haversted data:
```
  tools:
    - clearlydefined/1.3.3
    - licensee/9.12.1
    - scancode/3.2.2
```
and
```
    "3.2.2": {
      "_metadata": {
…        "headers": [
          {
            "tool_name": "scancode-toolkit",
            "tool_version": "3.0.2",

```

**Comment by jeffmcaffer** [comment]
This is intended. That version is the combination of the tool version and the configuration of the tool. When we tweak either, the version gets incremented accordingly. The data, as you show, has the actual tool version in it.

**Comment by pombredanne** [comment]
Ok got it, so the thing showing up in the UI is the schemaVersion and not the toolVersion?
```
    "3.2.2": {
      "_metadata": {
…            "type": "collection"
          }
        },
        "schemaVersion": "3.2.2",
        "toolVersion": "3.0.2",
```

**Comment by jeffmcaffer** [comment]
correct, it's the schema version. The intent is that the reader be able to tell exactly what went into that definition. It is not just the version of the tool but that + the configuration of that tool + the technique used to summarize the data from the tool.

**Comment by pombredanne** [comment]
thanks!
