### ISSUE TITLE
issue and website URLs should go in the `described.urls` property

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#483]
We semi-recently added a `described.urls` property to point to the download location etc for a component. We previously had `issueTracker` and `projectWebsite` properties. These latter two should be moved into the `urls` property. 

Note that the website may use these so may also need updating.

**Comment by ignacionr** [comment]
@geneh what's your opinion here; this PR is stalled because of its impact.

**Comment by geneh** [comment]
It looks like definitionsindexer name should be bumped and the schema version in definitionService should be reved for this change - see https://github.com/clearlydefined/service/pull/531. Can these changes be added to the PR?
We should also make sure to test these changes both with the old and the new schema thoroughly.

**Comment by nellshamrell** [comment]
Closing due to the related pull request (#531) being closed due to age. If this is still a concern please feel free to re-open.
