### ISSUE TITLE
curation requests are extremely slow

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#487]
This is only happening in prod

Opening the pull request hangs for minutes. 
The initial request times out, but then does eventually succeed and a PR shows up

It may be worth reaching out to github to see how it looks in their system. This is not a problem in dev.

My hunch is that this repo got added to a permanent abuser list for the insane number of HEAD requests we were making at it in a previous implementation.

If we can't get traction, we could consider migrating to a new repo like clearlydefined/curations or something like that, not ideal though.

**Comment by jeffmcaffer** [comment]
Hmmm, noticed that to... mail to support@github.com would likely sort it out

**Comment by jeffmendoza** [comment]
Check if still happening.

**Comment by jeffmendoza** [comment]
Seems ok now.
