### ISSUE TITLE
Add "OTHER" license tag

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/service#522]
The "NOASSERTION" license tag is overloaded in ClearlyDefined.  It both signifies (1) something requiring human attention to review and resolve and (2) that there is likely a non-SPDX-identifiable license in a given file.  When a human reviewer comes and looks at a file because of (1) but then confirms that, indeed, NOASSERTION is the correct tag because of (2) the curation community will be stuck in an infinite loop of curation.  

Adding an "OTHER" license tag that can only be put on a file by a human curator would break this loop.

**Comment by jeffmendoza** [comment]
This is done.
