### ISSUE TITLE
ClearlyDefined badges for projects

### ISSUE THREAD

**Issue by mynameistechno** [clearlydefined/service#54]
* Similar to Shields.io - have an end point that the URL contains your project details and serves up a project image/svg you can put in your markdown. 
* e.g. clearlydefined.io/badge/npm…
* Badge works out if you’ve met the criteria and serve up appropriate color badge (need to sort out what is the criteria for the 3 levels)

**Comment by mynameistechno** [comment]
We're going to start working on this. Some thoughts (questions)?
* The service has a route that serves up the actual image/svg
* The Curation class has a method that returns the "level" for the project (3 levels)
  * Need to sort out the criteria here. But for now we could do something simple, i.e. if license/copyright there it gets a 3. Only one of those it gets a 2. None, it gets a 1. Thoughts?
* The website page for the project should render the badge and provide some markdown they can copy/paste

**Comment by jeffmcaffer** [comment]
Generally sounds good. Perhaps add this as a separate "service" rather than adding to Curation just to keep separate concerns separate. 

Those badge levels sound fine to start. There will be more subtlety in the future but that's a good start.

**Comment by codeauroratsmart** [comment]
Sounds good @jeffmcaffer

**Comment by mynameistechno** [comment]
Resolved by #74

**Comment by rashmichitrakar** [comment]
@jeffmcaffer -- Is https://github.com/clearlydefined/service/pull/74 good enough for the demo or do we need to improve on the scoring algorithm?

**Comment by jeffmcaffer** [comment]
It's probably fine for now. it is more to illustrate the point than to make any claims. We might consider some tweaks. For example, 
* change the scale to a percent or something where it is more obvious what top marks is
* remove the colors. We have to walk a fine line here with casting judgement. For a team that doesn't care about copyrights, for example, who are we to say that that should be red? I'm honestly torn about this but it can be the sort of thing that causes a lot of churn. 

Actually on that last one, I recall GitHub introduced some "health metric" where they measured 4 or 5 things and then gave a score (likely with a badge). Perhaps that is a model to follow (or avoid).

**Comment by jeffmcaffer** [comment]
looking good. Thanks!
