### ISSUE TITLE
Discovered license in LICENSE.txt in root of repository did not populate declared license

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/service#559]
In this repository we found Apache-2.0 with high confidence in the LICENSE.txt but did not populate the declared license on the definition:
https://clearlydefined.io/definitions/git/github/davidebbo/webactivator/8a21247a5bdc61af3077bafceac602a9cb236875

**Comment by jeffmendoza** [comment]
Re-harvest with latest versions and see if still an issue.

**Comment by jeffmendoza** [comment]
Re-harvested with the same issue.

**Comment by nellshamrell** [comment]
Queued up a harvest in our dev environment to confirm there.

[(dev) webactivator](https://dev.clearlydefined.io/definitions/git/github/davidebbo/webactivator/8a21247a5bdc61af3077bafceac602a9cb236875)

**Comment by nellshamrell** [comment]
Closing as a duplicate of #759 and consolidating discussion there.
