### ISSUE TITLE
Incorrect license

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#566]
The tooling may have declared an incorrect license.  Please see https://github.com/clearlydefined/curated-data/pull/2058 for details.

**Comment by iamwillbar** [comment]
Moved to the service, it looks like the harvest data is correct and we just computed the definition incorrectly.

**Comment by ariel11** [comment]
@iamwillbar - another one - is this the same bug? https://github.com/clearlydefined/curated-data/pull/2110

**Comment by fossygirl** [comment]
@ignacionr Can you take a look?

**Comment by ignacionr** [comment]
This is looking like a summarizer issue -it consistently got to the conclusion that of GPL-3, on both pipy and git.

**Comment by fossygirl** [comment]
@ignacionr Do you need to do further investigation here, or how can we get this resolved?

**Comment by ignacionr** [comment]
Let's track summarizer issues as one on #603
