### ISSUE TITLE
Affected definitions open in new window

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#572]
On the Conversation tab, it is awesome to have the Affected definitions link directly to the component in ClearlyDefined.  It would be great though, if clicking on that link opened a new window.  Otherwise, I am back paging to get back to the PR.

**Comment by storrisi** [comment]
@ariel11 are you referring to the link generated in the PR , like https://github.com/clearlydefined/curated-data/pull/2110 ?

Unfortunately, that is markdown code, and it doesn't support opening links on a new tab. See https://github.com/mojombo/github-flavored-markdown/issues/28

**Comment by ariel11** [comment]
@storrisi - if you look on the Conversations tab - using  https://github.com/clearlydefined/curated-data/pull/2110  as an example - you will see where it says "Affected definitions," and under that "paramiko 2.6.0," which links to https://clearlydefined.io/definitions/pypi/pypi/-/paramiko/2.6.0/2.6.0 (and that is awesome).  But it would be helpful if clicking on that opened https://clearlydefined.io/definitions/pypi/pypi/-/paramiko/2.6.0/2.6.0 in a _new_ window, so I still have the PR open vs. hitting "Back" to get back to the PR.

**Affected definitions:
paramiko 2.6.0**

**Comment by storrisi** [comment]
@ariel11 thanks for replying so quickly on this :)

As i said above, that text is generated by markdown code, the same that we are using here to comment this issue.
Markdown doesn't support any command that gives the ability to open an URL on a new page, as HTML instead does.

**Comment by geneh** [comment]
Closing since the markdown does not support this option.
