### ISSUE TITLE
Contribution ERROR: Source location must be an object 

### ISSUE THREAD

**Issue by AE49** [clearlydefined/service#583]
@fossygirl @ignacionr @geneh I am opening a new issue. I'm getting the same "Contribution ERROR: Source location must be an object" as clearlydefined/website#779 for the following components:

•	git/github/antaris/razorengine/4399028120f3c570fc8049fba9c055ac9be81468
•	git/github/automattic/cli-table/e35ccee7341e8574839df751a8aa10acd5a82a5b
•	git/github/azure/azure-docker-extension/0dd2f199467db78e91d28c30d8595d1bcaf776de
•	git/github/azure/azure-docker-extension/2727dce2785d0a3cdca692387b0acee36b908351
•	git/github/azure/azure-docker-extension/8c5236a9ab19fabd2fb77c606b419caad376f6d7
•	git/github/azure/azure-linux-extensions/3093bb8af7f652e59486c99ba3814d1db3e88b66
•	git/github/azure/azure-linux-extensions/9c96c34f085c0212430330ff11f1c68170403697
•	git/github/azure/azure-linux-extensions/fa375841072581690bbd23a929db1aa453973dac

If you can help resolve.

**Comment by ignacionr** [comment]
Thanks to @AE49 calling and sharing screen, we could find the root cause of these problems.
Another issue was created with the fix required in the website https://github.com/clearlydefined/website/issues/792
