### ISSUE TITLE
Declared license not populating

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/service#585]
In [this example](https://clearlydefined.io/definitions/git/github/suitcss/components-test/7dc65fc33cd463fce87180fd83dc83deea1864f8), scancode correctly identifies that LICENSE.md is MIT, there are no other discovered licenses, but the declared license field is not populated.  

Why the mismatch?

**Comment by royaljust** [comment]
Another [example](https://clearlydefined.io/definitions/git/github/xeipuuv/gojsonpointer/e0fe6f68307607d540ed8eac07a342c33fa1b54a)

**Comment by royaljust** [comment]
And [another](https://clearlydefined.io/definitions/git/github/macton/libdot/be8c52cb78b27f941534abcff6f111c7ca4235e0)

**Comment by ariel11** [comment]
Yes, I run into thsoe too - here's one: https://clearlydefined.io/definitions/git/github/driftyco/ionic-site/a914b37f41bd0968c2a3db6e3436be9b44b7f4aa.  The License file is Apache, but the Declared license field is lefr blank.  @fossygirl or @geneh  what logic is the tooling following when it does not fill in the Declared license field in instances like this, or is this a bug?   Thanks!

**Comment by nellshamrell** [comment]
Queued some of these to be harvested in the dev environment to try and reproduce:
* [(dev) gojsonpointer](https://dev.clearlydefined.io/definitions/git/github/xeipuuv/gojsonpointer/e0fe6f68307607d540ed8eac07a342c33fa1b54a)
* [(dev) ionic-site](https://dev.clearlydefined.io/definitions/git/github/driftyco/ionic-site/a914b37f41bd0968c2a3db6e3436be9b44b7f4aa)
* [libdot](https://dev.clearlydefined.io/definitions/git/github/macton/libdot/be8c52cb78b27f941534abcff6f111c7ca4235e0)

**Comment by nellshamrell** [comment]
This appears to be related to #759. Closing as a duplicate and consolidating discussion to that issue.
