### ISSUE TITLE
Do not use https://mvnrepository.com or https://search.maven.org as URLs for Maven

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/service#588]
Several (if not all) Maven packages use a URL such as https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api

This is not the proper an canonical URL for Maven in general. This is a search engine that is supported by ads ... so if this were a general purpose URL, this would be similar to provide a Google search URL instead of a direct URL to a web site and it really does not make sense both from a technical and from a community point of view.

We should instead point to each repositories (and primarily to Maven Central instead) Here this would be http://central.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.5/

**Comment by pombredanne** [comment]
Also we should not use https://search.maven.org/remotecontent?filepath=jakarta/ejb/jakarta/ejb-api/3.2.5/jakarta.ejb-api-3.2.5-sources.jar as a source URL instead we should use the direct URL on the Maven repo (for central either https://central.maven.org/ or https://repo1.maven.org/)

Using https://search.maven.org/remotecontent is again using a search engine URL as a reference URL which does not make sense to me.

**Comment by pombredanne** [comment]
See https://github.com/clearlydefined/curated-data/pull/2213#issuecomment-516312330

**Comment by ignacionr** [comment]
Thank you @pombredanne for this. Do you have set steps to obtain the canonical URL from the search engine URL?

Also, it seems that https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api is a package name that would convert into multiple releases.

Taking all of this into account, what is your suggestion as to how to treat URLs like the ones you mention? Reject them/propose changes/create a tool that visits our assets and corrects these?

**Comment by bduranc** [comment]
@pombredanne 

> Several (if not all) Maven packages use a URL such as https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api
> 
> This is not the proper an canonical URL for Maven in general. This is a search engine that is supported by ads ... so if this were a general purpose URL, this would be similar to provide a Google search URL instead of a direct URL to a web site and it really does not make sense both from a technical and from a community point of view.
> 
> We should instead point to each repositories (and primarily to Maven Central instead) Here this would be http://central.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.5/

Interestingly, I notice that the only "drag and drop" URL for Maven that appears to be supported by CD Workspace is from this mvnrepository.com search engine website.

The below picture shows my attempt at drag-and-drop of full URLs to the CD Workspace:

https://repo1.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.5/ ["not supported"]
http://central.maven.org/maven2/jakarta/ejb/jakarta.ejb-api/3.2.5/ ["not supported"]
https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api ["needs version"]
https://mvnrepository.com/artifact/jakarta.ejb/jakarta.ejb-api/3.2.5 [successful]

![image](https://user-images.githubusercontent.com/31491646/62171257-394a4600-b2e3-11e9-830f-292831b7718f.png)

I don't know if anyone else has come to the same observation or not.

**Comment by storrisi** [comment]
I've created https://github.com/clearlydefined/website/issues/831 to track the problem reported by @bduranc

**Comment by ariel11** [comment]
@storrisi 
Are we still looking into updating the links ClearlyDefined uses for Maven packages?  Right now, each maven package points to https://mvnrepository.com and points there as well for the sources.jar.  As discussed at the top of this issue, these links should be updated to the locations mentioned above.
(Cc. @pombredanne)

**Comment by geneh** [comment]
It looks like all Maven definitions pointing to https://mvnrepository.com/artifact need to be re-computed. Reopening to address.
