### ISSUE TITLE
Coordinate casing differs between request and response

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/service#589]
If you do a `POST` to `/definitions` with coordinates that have mixed casing the casing of the keys in the response does not match meaning you can't easily correlate the request and the response without doing some form of normalization. I think the casing of the keys in the response should match the casing from the request, the canonical casing can be inside the object but the key's casing should match the request.

Request:
```json
[
	"npm/npmjs/-/testTest/0.0.0",
	"npm/npmjs/-/express/4.17.1",
	"npm/npmjs/-/express/4.17.0"
]
```

Response (trimmed):
```json
{
    "npm/npmjs/-/testtest/0.0.0": {
      ...
    },
    "npm/npmjs/-/express/4.17.1": {
      ...
    },
    "npm/npmjs/-/express/4.17.0": {
      ...
    }
}
```

**Comment by ignacionr** [comment]
What would you think of a permanent redirect? Wouldn’t it be more semantically correct?

**Comment by ignacionr** [comment]
Got it; we can do this, and I will take a look at how it affects our curations with case-only differences.

**Comment by iamwillbar** [comment]
Thanks, I don't think this should affect curations as this **should not** impact the data itself, this is just the response/request payloads.

**Comment by geneh** [comment]
https://github.com/clearlydefined/service/pull/590 has been reverted

**Comment by ignacionr** [comment]
This issue is reopened, for the plan to resolve see #604

**Comment by ignacionr** [comment]
We will resolve this request as it was before, but we will add an optional parameter ```matchCasing=false``` that the website will use, in order to maintain the result in consistency with the underlying data (as opposed to matching the request).

**Comment by ignacionr** [comment]
This was done.

**Comment by geneh** [comment]
@ignacionr I believe it wasn't done. `matchCasing` parameter was added in definitions-find.json to prevent bad request error but it wasn't actually implemented. Could you please double check?

**Comment by ignacionr** [comment]
Let me find the PR or the branch. Will check.
