### ISSUE TITLE
Clean up copyrights in summarized data

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#59]
The data output from Scancode, particularly around copyrights is pretty noisy. Random characters, duplicates that differ only by case, puncutation, Inc. vs Inc vs Incorporated, ... 

This degrades the apparent quality of the data for the end user so is key to showing value and building trust.

We can implement this in several different places. Ideally the upstream tools would just be less noisy but ... Current thinking is to put this in the summarizers. There is a summarizer for each tool so each would do the work as it goes from the raw data form to the summarized/canonical form. This might be a shared bit of code that does all the simplifications but rather than introduce a new step in the flow, consider adding it to summarization.

**Comment by fossygirl** [comment]
@tsteenbe @pombredanne Could I get an update here? I think I saw some talk about this in Slack the other day, but I wanted to confirm where this is?

**Comment by jeffmcaffer** [comment]
The changes to ScanCode are not available yet so we'll have to do something simple in the service. Basically in the scancode.js summarizer we need to trim off punctuation and whitespace, do case insensitive compare, break on `and`, look for `<` and `>` chars, ... Keep it simple for now. As with many things, there may be an NPM for that.

Great hackathon project.

**Comment by pombredanne** [comment]
@jeffmcaffer changes in ScanCode have been pushed as part of https://github.com/nexB/scancode-toolkit/issues/930 
I still need to document the rationale for summarization with a bunch of examples.

**Comment by jeffmcaffer** [comment]
The consensus seems to be that we will go for "statement" information wrt copyrights, not just holders. This  will bring a different set of problems wrt copyright data coalescing and slight variations in spelling and punctuation etc. Let's close this issue and cross that bridge when we come to it.

**Comment by pombredanne** [comment]
@jeffmcaffer fair enough, both summaries/coalescing are available in ScanCode in anycase.
