### ISSUE TITLE
Cover app.js with a few tests to prevent basic regressions

### ISSUE THREAD

**Issue by ignacionr** [clearlydefined/service#595]
### Given:
- it's convenient to modify parts of the program independently, covering their intended behavior with tests
- unit tests currently do not apply to the startup phase of running the service -as exemplified by PR #590 introducing an error preventing it from start
- expanding test coverage is an implicit goal

### Goals:
- keep the convenience
- protect us from changes that break the service initial phase

## Proposal
Cover app.js createApp phase with at least a basic test, that will fail when setup is not possible.

**Comment by geneh** [comment]
👍
