### ISSUE TITLE
Curation status check fails

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#609]
Status check fails for the following curation: https://github.com/clearlydefined/curated-data/pull/2316

Besides resolving this problem, it would be super helpful to add logging for whenever a status check fails.

@ariel11 FYI

**Comment by ignacionr** [comment]
The yaml file had been rendered invalid. Simple issue, but difficult to find.

**Comment by geneh** [comment]
@ignacionr, is it possible to add a logging message to whenever a status check fails? It may save us a lot of time in the future.
