### ISSUE TITLE
REST API as mentioned in both Swagger docs and CD GH docs are out of date/inconsistent

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/service#614]
**Issue Type:** Bug
**Issue Description:**

Someone already mentioned the Swagger docs were out of date in issue #541. But both the Swagger API docs (https://api.clearlydefined.io/api-docs/#/curations/patch_curations) and the CD GH docs (https://docs.clearlydefined.io/using-data#curation) appear incorrect.

I first noticed this when experimenting with the Curation API.

The only way that has worked for me is what the public ClearlyDefined.io UI is calling to the Service when a user submits a curation.

This works for me (website ClearlyDefined.io):
PATCH: `https://dev-api.clearlydefined.io/curations`

BODY: 
```
{ 
   "contributionInfo":{ 
      "summary":"[Test] Update declared license",
      "details":"The declared license should be Apache as per the LICENSE file.",
      "resolution":"Updated declared license to Apache-2.0.",
      "type":"incorrect",
      "removeDefinitions":false
   },
   "patches":[ 
      { 
         "coordinates":{ 
            "type":"git",
            "provider":"github",
            "namespace":"aspnet",
            "name":"aspnetkatana",
            "revision":"64bf627964ca9bd312cfda31916194212731c11c"
         },
         "revisions":{ 
            "64bf627964ca9bd312cfda31916194212731c11c":{ 
               "licensed":{ 
                  "declared":"Apache-2.0"
               }
            }
         }
      }
   ]
}
```
RESPONSE: `HTTP 200 (OK)`
DETAILS:
```
 {
    "prNumber": 920,
    "url": "https://github.com/clearlydefined/curated-data-dev/pull/920"
}
```

This doesn't (existing Swagger docs):
PATCH: `https://dev-api.clearlydefined.io/curations`

BODY: 
```
{
  "coordinates": {
    "type": "git",
    "provider": "github",
    "namespace": "aspnet",
    "name": "aspnetkatana"
  },
  "revisions": { "64bf627964ca9bd312cfda31916194212731c11c":{"licensed":{"declared":"Apache-2.0"}}}
}
```
RESPONSE: `HTTP 500 `
DETAILS: `"Cannot read property 'forEach' of undefined"`

and this doesn't either (taken from CD GH docs):
PATCH: `https://dev-api.clearlydefined.io/curations/git/github/aspnet/aspnetkatana/64bf627964ca9bd312cfda31916194212731c11c`

BODY: 
```
{ 
   "description":"[Test] Update license and source location",
   "patch":{ 
      "described":{ 
         "sourceLocation":{ 
            "type":"git",
            "provider":"github",
            "url":"https://github.com/aspnet/aspnetkatana",
            "revision":"64bf627964ca9bd312cfda31916194212731c11c"
         }
      },
      "licensed":{ 
         "license":{ 
            "expression":"Apache-2.0"
         }
      }
   }
}
```
RESPONSE: `HTTP 404`
DETAILS: `"Error: Not Found"`

**Comment by ignacionr** [comment]
Let me take a look too. Also happy to keep it separate from swagger validity.

**Comment by mawentowski** [comment]
I am a technical writer looking to join an open source project to document RESTful APIs. I currently have 7 years experience as a technical writer that includes experience with "docs as code" workflows, Git, and static sites. I am venturing into the world of APIs and was wondering if you currently have any tasks you need assistance with?

**Comment by geneh** [comment]
Thanks for the interest! Please feel free to contribute.

**Comment by ignacionr** [comment]
PR #620 will fix the swagger; we still need someone to help with the doc at https://docs.clearlydefined.io/using-data#curation please.
