### ISSUE TITLE
Error when calling /definitions from the website

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#618]
On Browse page when trying to select any type, getting the following error for https://api.clearlydefined.io/definitions?matchCasing=false&sort=releaseDate&sortDesc=true&type=npm: 
`data A definitions query may not contain additional properties`

It is related to https://github.com/clearlydefined/website/pull/824 (everything works as expected when the new matchCasing parameter is removed).

@ignacionr @storrisi Can we fix it quickly without rolling https://github.com/clearlydefined/website/pull/824 back?

**Comment by geneh** [comment]
@ignacionr Any update on this?

**Comment by ignacionr** [comment]
This is ready; let me create the PR.
