### ISSUE TITLE
NuGet curations submitted to incorrect file

### ISSUE THREAD

**Issue by capfei** [clearlydefined/service#622]
The site pulls up the curation information for NuGets with capitalized names from the uppercase file name, but submitted curations go to the lowercase files in the curated-data repo.

Examples:
PRs submitted with no changes:
https://github.com/clearlydefined/curated-data/pull/2500
https://github.com/clearlydefined/curated-data/pull/2503

Files in curated-data repo:
https://github.com/clearlydefined/curated-data/search?q=microsoft.aspnetcore.httpspolicy&unscoped_q=microsoft.aspnetcore.httpspolicy

https://github.com/clearlydefined/curated-data/search?q=microsoft.extensions.hosting&unscoped_q=microsoft.extensions.hosting

CD site:
https://clearlydefined.io/share/eJyTMuEyyCtNTy3Rh5C6+r6ZyUX5xflpJXquFSWpecWZ+XnFeh75xSWZeen6RnpGegZCDFIWXCa4dDkWF/illjjnF6XqeZSUFBQH5OdkJlfCdAIASTglAg==

**Comment by capfei** [comment]
Another PR with a similar issue: https://github.com/clearlydefined/curated-data/pull/2508

https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Microsoft.AspNetCore.Authentication.Cookies.yaml is the file but the PR wants to create a new file that is lowercase.

**Comment by capfei** [comment]
Any PRs I processed yesterday that are NuGets with uppercase names will have this issue like https://github.com/clearlydefined/curated-data/pull/2496.

**Comment by fossygirl** [comment]
@geneh @ignacionr Can you please look into this ASAP?

**Comment by ignacionr** [comment]
Working on this now

**Comment by ignacionr** [comment]
@capfei kindly help us retry, and re-open this issue if needed. Also notice that the PRs referred to contain no file changes (they have no contents), so the problem appeared at its creation (not afterwards, at merging time).
We're tracking all related issues [here](https://github.com/clearlydefined/service/issues/626#issuecomment-540533384).
