### ISSUE TITLE
Merged curations showing as NOASSERTION

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#625]
Justin noticed a merged curation still shows as NOASSERTION - https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnetcore.authentication.jwtbearer/2.2.0. 
The PR shows as merged: https://github.com/clearlydefined/curated-data/pull/2497.
The component shows as NOASSERTION.
![image](https://user-images.githubusercontent.com/17935946/65902695-d96a2d00-e36f-11e9-8b0e-c307d2652082.png)

**Comment by ariel11** [comment]
@capfei and @fossygirl as FYI

**Comment by geneh** [comment]
@ignacionr Is it related to https://github.com/clearlydefined/service/issues/622? Could it be because of the casing mismatches?

**Comment by ignacionr** [comment]
This was manually resolved with [PR 2528](https://github.com/clearlydefined/curated-data/pull/2528); the issue seems to have been casing.

**Comment by geneh** [comment]
Here is another case of the same issue:
https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Extensions.Http/2.2.0

1. @ignacionr Has it been resolved for all future curations?
2. @ignacionr We need to make sure all open and merged curations have the right casing for NuGet packages as in https://github.com/clearlydefined/curated-data/pull/2528. Please let me know if any help is required in identifying the affected PRs. Basiaclly, it should be as simple as comparing the NuGet packages names in the curated-data repo to the ones in ClearlyDefined, for example by using definitions web API.
@royaljust FYI

**Comment by geneh** [comment]
@ignacionr Could you please update this issue based on your comments in Discord channel?

**Comment by ignacionr** [comment]
As stated before, the case of https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Extensions.Http/2.2.0 is that it got within the window of time where we had the new casing-matching feature, but no flag to disconnect. This was resolved manually by https://github.com/clearlydefined/curated-data/pull/2618 ; currently investigating if there are more in this situation.

**Comment by geneh** [comment]
There are 78 curation yaml files with both correct and incorrect file names, for example Respond.yaml and respond.yaml. Both sets of files contain curations and need to be merged. I'll update the files accordingly.

**Comment by geneh** [comment]
The yaml files have been updated.
