### ISSUE TITLE
Alert Notification "Invalid curations" raised for "clearlydefined-api-prod"

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#631]
```
exceptions 
| where outerMessage has 'Invalid curations:' or outerMessage has 'intended curations are invalid'
| summarize count() by outerMessage
```
10 occurances of 
Invalid curations: curations/nuget/nuget/-/microsoft.aspnetcore.authentication.jwtbearer.yaml

@ignacionr @storrisi Could you please check this one?

**Comment by ignacionr** [comment]
These were created by me. Reported what's needed in [here](https://github.com/clearlydefined/service/issues/630). The reason the curation was originally deemed invalid is because it contained a file deletion.
