### ISSUE TITLE
Number of changed files not matching contributions

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#641]
This person contributed 18 changes in this PR (https://github.com/clearlydefined/curated-data/pull/2588), but then it only shows 4 changed files?

**Comment by jeffmendoza** [comment]
There are a bunch of empty commits on that PR, need to investigate.

**Comment by nellshamrell** [comment]
@ariel11 Have you seen this behavior with any other PRs?

**Comment by ariel11** [comment]
@nellshamrell - we haven't received a PR with multiple components curated in a long time, so no other examples to show.

**Comment by nellshamrell** [comment]
Ok, going to close this, then, but please feel free to re-open if you see this behavior again.
