### ISSUE TITLE
Improve EULA licenses detection as Other for NuGet packages based on licenseUrl

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#652]
NuGet packages that have licenseUrl defined pointing to EULA licenses should have their declared licenses defined as OTHER.

FYI @royaljust @ariel11 @fossygirl

**Comment by geneh** [comment]
FYI @capfei 
~27K NuGet packages with EULA licenseUrl should now have OTHER declared license.
A few examples:
https://clearlydefined.io/definitions/nuget/nuget/-/coderushserver/18.2.8.191141507
https://clearlydefined.io/definitions/nuget/nuget/-/dlhsoft.ganttchartweblibrary/5.1.6.5
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnet.identity.entityframework.cs/2.0.0
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnet.identity.entityframework.ja/2.0.0-alpha1
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnet.signalr.core.ko/2.0.1
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnet.webapi.client.it/5.0.0-rc1
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnetcore.authentication.jwtbearer/2.0.0-preview2-final
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.aspnetcore.server.httpsys/2.0.2
https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.codeanalysis.common/1.1.1
Does it look right?

**Comment by ariel11** [comment]
@geneh - I spot-checked a few and agree with OTHER.  This is great!!!

**Comment by capfei** [comment]
@geneh I checked a few and they look correct. Thanks! 😃
