### ISSUE TITLE
Remove dependency on CosmosDB/MongoDB

### ISSUE THREAD

**Issue by geneh** [clearlydefined/service#660]
CosmosDB costs almost half of Azure bill. CosmosDB also adds complexity to the system.
We should explore other alternatives, such as Azure Table combined with the already used Azure Search if needed.

**Comment by pombredanne** [comment]
@geneh in doing so why not consider also something that would not be tied to a given cloud provider?
What about some good ole relational DB like PostgreSQL?

**Comment by geneh** [comment]
That's an option too. Thanks!

**Comment by pombredanne** [comment]
Using a simple open source database would be a much better option (including and in particular for local deployment as using the proprietary-licensed MongoDB is IMHO not an acceptable option).
See also #750 for a related storage ticket for the JSON files.

I cannot fathom any issue with a relational database:
1. it will take less space
2. the schema-less appeal of a document database is great when you have really unstructured documents, but the schema is pretty stable here and we are not dealing with unstructured documents for definitions.
3. it will be possible to install locally without MongoDB or a cloud storage service

**Comment by pombredanne** [comment]
@geneh just to restate my opinion here:

You wrote initially:

>  We should explore other alternatives, such as Azure Table combined with the already used Azure Search if needed.

Anything that would not be installable locally using an clearly open source solution and that would be be cloud only (e.g. some Azure service) would be a no-no in my book. The initial choice of CosmosDB and the dual-licensed MongoDB looks like a mistake to me in hindsight, as there is no open source local deployment available anymore.

**Comment by nellshamrell** [comment]
We discussed this at today's meeting and decided that this isn't something we will do at this point. If this becomes a pain point in the future, we can certainly re-open it.

Here are the notes from the discussion:
* No “monetary reason” to do this as this point - Microsoft is covering the Azure costs of the ClearlyDefined project
* Local installations of Mongo _do_ seem to be working with the [new local dev environment setup](https://github.com/clearlydefined/docker_dev_env_experiment)
* No urgent reason to switch to a relational database
* Funders might rather see funds go towards working on the project; not for infrastructure if avoidable
* Funds not a problem for now.
* Just close - no objections
