### ISSUE TITLE
npm test is noisy

### ISSUE THREAD

**Issue by tmarble** [clearlydefined/service#676]
In running `npm test` locally and, apparently, in CI as demonstrated in a recent 
[build](https://clearlydefined.visualstudio.com/ClearlyDefined/_build/results?buildId=6665) there are two Deprecation warnings and one exception thrown _but_ the tests apparently pass:

```
   ✓ should handle falsy input
Utils extractDate
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format.

    ✓ validates valid PR change
Exception: 
Error: Invalid curations: 
    at AzureApplicationInsightsLogger.log (/home/tmarble/src/github/clearlydefined

    ✓ getCuration should access tree with children
(node:855475) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security

```
@geneh could you please help me understand if the Exception _should_ cause **npm test** to fail -or- can be safely ignored. If the former then a separate issue should be filed to figure out how to get the exception to cause the test to fail.

In either case this bug is to find and fix the Deprecation warnings (and possibly the source of the exception).

**Comment by geneh** [comment]
`validates invalid PR change` test has a call to a method that fails and the test passes as expected.
