### ISSUE TITLE
Can we run scan tools over license URL on nuspec?

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#692]
On NuGet packages, I will see a licenseurl on the nuspec file, but sometimes I still have to manually curate that license for the declared license. 

Is it possible to run the scan tools over the licenseurl on nuspec files? 

* Example - https://clearlydefined.io/definitions/nuget/nuget/-/NuGet.Packaging.Core.Types/3.5.0-beta2-1484
* Nuspec - https://clearlydefined.io/file/1c5a1e884b6c0644c5d60059c0cba1460268518fadb453eaed58facf45575214
* licenseUrl - https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/LICENSE.txt</licenseUrl>
* Declared license should be Apache-2.0

**Comment by geneh** [comment]
I'll re-run summarizers for all the versions of NuGet.Packaging.Core.Types and comment when it's done.
https://clearlydefined.io/?type=nuget&sortDesc=true&sort=releaseDate&name=NuGet.Packaging.Core.Types

**Comment by geneh** [comment]
Done!
