### ISSUE TITLE
Scancode not being run on all NuGets?

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#695]
I understand scancode is set to run on all NuGets, however I am running into some that have not - e.g. https://clearlydefined.io/definitions/nuget/nuget/-/Mono.Posix.NETStandard/1.0.0-beta2.  Is this a bug?  

To resolve, should I request the component be harvested (again) using the ClearlyDefined API?

**Comment by geneh** [comment]
I've re-harvested it using the UI at https://clearlydefined.io/harvest:

![Screen Shot 2020-01-08 at 1 24 16 PM](https://user-images.githubusercontent.com/1537662/72017648-f3db5e80-321a-11ea-8de4-23e801b9ef12.png)
