### ISSUE TITLE
Ability to upload custom license text

### ISSUE THREAD

**Issue by clearlyoss** [clearlydefined/service#697]
Unless I'm missing it, CD doesn't have the ability to upload/represent custom license text that is something other than an SPDX format.  For many license attributions they can be mapped to a SPDX license; however there a number of license that can't be represented with the drop down SPDX list that CD has available.  To represent these you can note that the license is OTHER but I don't see a way to upload the actual license TEXT.  Below is an example of a license format that is non-SPDX that needs attribution:

MICROSOFT REFERENCE SOURCE LICENSE (MS-RSL)

This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.

1. Definitions
The terms "reproduce," "reproduction" and "distribution" have the same meaning here as under U.S. copyright law.

"You" means the licensee of the software.

"Your company" means the company you worked for when you downloaded the software.

"Reference use" means use of the software within your company as a reference, in read only form, for the sole purposes of debugging your products, maintaining your products, or enhancing the interoperability of your products with the software, and specifically excludes the right to distribute the software outside of your company.

"Licensed patents" means any Licensor patent claims which read directly on the software as distributed by the Licensor under this license.

2. Grant of Rights
(A) Copyright Grant- Subject to the terms of this license, the Licensor grants you a non-transferable, non-exclusive, worldwide, royalty-free copyright license to reproduce the software for reference use.

(B) Patent Grant- Subject to the terms of this license, the Licensor grants you a non-transferable, non-exclusive, worldwide, royalty-free patent license under licensed patents for reference use.

3. Limitations
(A) No Trademark License- This license does not grant you any rights to use the Licensor's name, logo, or trademarks.

(B) If you begin patent litigation against the Licensor over patents that you think may apply to the software (including a cross-claim or counterclaim in a lawsuit), your license to the software ends automatically.

(C) The software is licensed "as-is." You bear the risk of using it. The Licensor gives no express warranties, guarantees or conditions. You may have additional consumer rights under your local laws which this license cannot change. To the extent permitted under your local laws, the Licensor excludes the implied warranties of merchantability, fitness for a particular purpose and non-infringement.

**Comment by nellshamrell** [comment]
This is related to https://github.com/clearlydefined/curated-data/issues/7836

**Comment by nellshamrell** [comment]
Discussed in the week's community meeting. Here are the notes: 

* Should ClearlyDefined stop only accepting SPDX licenses?
* License ref proposal - normalize license text and be able to identify it as SPDX
* Consider implementing license ref functionality
* Close issue in service and keep curated data issue open
* https://github.com/python/peps/blob/master/pep-0639.rst
* Keep the issues of 1) how to literally indicate the license vs 2) the license itself being clear

Before we can consider an implementation (like this one) we need to complete the discussion in https://github.com/clearlydefined/curated-data/issues/7836

Closing for now.
