### ISSUE TITLE
Curation PRs have less useful title 

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#738]
somewhere along the way either the code or the practices changed such that the curation PRs have very generic titles (e.g., Add Declared License) vs including an indication of component the PR affects as shown in this screenshot from the past. 
![image](https://user-images.githubusercontent.com/10070956/81016568-8ed4f580-8e15-11ea-939c-4665586e31ab.png)
 
The component being curated is pretty key info. In these generic title PRs the component is hidden as the last line in the first comment. IMO the component id/version should be in the title so that someone looking through the PRs can understand what they affect.

**Comment by nellshamrell** [comment]
Taking a look at the current list of PRs: https://github.com/clearlydefined/curated-data/pulls

I think this was fixed at some point.

@jeffmendoza and/or @jeffmcaffer could you confirm?

**Comment by nellshamrell** [comment]
Going to go ahead and close this, but if anyone sees this issue in the future please feel free to re-open!
