### ISSUE TITLE
Get components definitions fails when one of components is unformatted

### ISSUE THREAD

**Issue by noaabarki** [clearlydefined/service#742]
When requesting definitions for a list of components that includes an unformatted entry(for example:  "npm/npmjs/redie/0.3.0") the request failes for all components and returns uninformative error: 

`{
  "error": {
    "code": "500",
    "message": "An error has occurred",
    "innererror": {}
  }
}`

**Comment by nellshamrell** [comment]
To replicate:

### Successful call: 

```bash
curl -X POST "https://api.clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"git/github/microsoft/redie/194269b5b7010ad6f8dc4ef608c88128615031ca\",\"npm/npmjs/-/redie/0.3.0\"]"
```

Returns

```bash
{
  "npm/npmjs/-/redie/0.3.0": {
    "licensed": {
      "declared": "MIT",
      "toolScore": {
        "total": 73,
        "declared": 30,
        "discovered": 13,
        "consistency": 0,
        "spdx": 15,
        "texts": 15
      },
      "facets": {
        "core": {
          "attribution": {
            "unknown": 2,
            "parties": [
              "Copyright (c) Microsoft Corporation."
            ]
          },
          "discovered": {
            "unknown": 0,
            "expressions": [
              "MIT",
              "NOASSERTION"
            ]
          },
          "files": 4
        }
      },
```

### Unsuccessful call:

```bash
curl -X POST "https://api.clearlydefined.io/definitions" -H "accept: application/json" -H "Content-Type: application/json" -d "[\"npm/npmjs/redie/0.3.0\",\"npm/npmjs/-/redie/0.3.0\"]"
```

Returns

```bash
{
  "error": {
    "code": "500",
    "message": "An error has occurred",
    "innererror": {}
  }
}
```

It should return the definition of the valid component, even if getting the definition of the invalid component fails.

**Comment by nellshamrell** [comment]
Troubleshooting notes:

My first thought was this had to be triggered somewhere in the [list definitions route here](https://github.com/clearlydefined/service/blob/71bd0c3cff20330b0c5013cb6ee926c3f5033f72/routes/definitions.js#L65). Strangely, though, if one of the list of components is malformed, it doesn't get to that route at all.

Investigating further.
