### ISSUE TITLE
Finalize storage structure

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#76]
Need to finalize the storage structure path before our OSLS demo.

**Comment by jeffmcaffer** [comment]
In our filesytem and blob storage providers we store artifacts with /revision and /tool segments. That is a bit of a legacy from before we really understood coordinates and there were various scenarios with optional segments etc. In the case of stores, it is unclear that there really are optional segments. 

For example, the store always stores the tool output for a revision of a component. So there is always a _revision_ segment and there is always a _tool_ and _toolVersion_. We could remove these and simplify the structure/code some. 

This has caused some folks confusion as they look on disk at the samples and see these segments and then think that they should be included in the various urls.

@iamwillbar would like your thoughts on this. The only real downside I can see is that if, in the future, we want to store component level info, we have the possibility of a collision with the name of the component sub-element name and a component revision name.

**Comment by jeffmcaffer** [comment]
closing. not worth doing IMHO
