### ISSUE TITLE
Some Copyrights are shown with ", Contributors" stripped of

### ISSUE THREAD

**Issue by FlorianSW** [clearlydefined/service#767]
During some look up of some components I came across some harvested data, that seems to miss a part of the copyright.

Here are two examples:
https://clearlydefined.io/definitions/npm/npmjs/-/y18n/4.0.0
https://clearlydefined.io/definitions/npm/npmjs/-/yargs-parser/13.1.2

Both of them show a copyright in this format:
"Copyright (c) YYYY"
while their LICENSE file shows a copyright in this format:
"Copyright (c) YYYY, Contributors"

As the license file gives the copyright how it should be used in, e.g., "used oss libraries" reports, the copyright should be taken over from the license file as a whole. The ", Contributors" part should not be stripped off.

If you need more information, I'll try to give them :)

**Comment by jeffmcaffer** [comment]
Looking at the harvested data in the ClearlyDefined UI (see Harvested tab at bottom) it looks like ScanCode is giving that truncated value for the copyright. the FOSSology Copyright tool gives the full copyright. IIRC ClearlyDefined favors ScanCode over FOSSology in the case of copyrights (there were a number of other issues that drove that). 

So, not to pass it off but it feels like something that should be taken up with the ScanCode folks.

**Comment by FlorianSW** [comment]
Sounds fair enough :) I think I also found a related issue from August last year as well:
https://github.com/nexB/scancode-toolkit/issues/2172

I'll check that, however, I think we can close this issue here for now :) Thanks for your answer!
