### ISSUE TITLE
Rename everything

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#77]
We need to rename everything in the code and get the code hygiene up now that we've moved along conceptually and in development.

**Comment by rashmichitrakar** [comment]
@fossygirl - Rename to what?

**Comment by fossygirl** [comment]
@jeffmcaffer tells me that we have names in the code that for example use the same name for multiple things or references an old concept. So we need to name things appropriately and individually now that the concepts and the code have moved along.

**Comment by rashmichitrakar** [comment]
@jeffmcaffer self assigned this in the website (https://github.com/clearlydefined/website/issues/45), does it makes sense for 1 person to do both bits?
