### ISSUE TITLE
public-suffix-list.txt

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#772]
See https://github.com/clearlydefined/curated-data/pull/7659.  Unclear where the tooling is pulling the public-suffix-list.txt from?  Any ideas? 

![image](https://user-images.githubusercontent.com/17935946/97768633-80744780-1ae1-11eb-9e7b-6ad6091facf3.png)

**Comment by waynebeaton** [comment]
While I'm at it... all of the files associated with the record are *.class files, but the content of the source field points to an archive that contains *.java files (as would be expected). It does not appear that the files associated with  [httpclient5 5.0.3](https://clearlydefined.io/definitions/maven/mavencentral/org.apache.httpcomponents.client5/httpclient5/5.0.3/5.0.3) come from the source. Is my expectation wrong?

**Comment by nellshamrell** [comment]
I will take a look at this this week!

**Comment by jeffmcaffer** [comment]
Looks like that file is legit (see comments in https://github.com/clearlydefined/curated-data/pull/7659) so this issue should be closed.  The topic around maven source urls/content is covered in another issue
