### ISSUE TITLE
Upgrade to a more current Date/Time parser

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/service#789]
According to the npm page for [moment](https://www.npmjs.com/package/moment), "Moment.js is a legacy project, now in maintenance mode. In most cases, you should choose a different library."

We should upgrade to a non-legacy library.

**Comment by qtomlinson** [comment]
[Recommendations ](https://momentjs.com/docs/#/-project-status/recommendations/)

**Comment by nellshamrell** [comment]
This was fixed with #897
