### ISSUE TITLE
Keep an active list of dependency relations

### ISSUE THREAD

**Issue by RichardLitt** [clearlydefined/service#797]
It would be useful to be able to access dependency trees. I can think of a few use cases:
- Eliminating the need to search dependencies which have already been searched (perhaps known dep trees could be hashed using something like IPFS to eliminate double-checking);
- Mining for cases besides licensing. There are some projects, such as [FairOSS](https://faiross.org/) and [Flossbank](https://flossbank.com/) which are trying to algorithmically financially support dependencies, which could benefit from this knowledge.
- Sharing dependency graphs between organizations to coordinate support or issue triage.

**Comment by fossygirl** [comment]
The project has so far made a very concerted decision to not try to track or resolve dependencies. This is because it is such a difficult problem to solve and also because there are other projects addressing this use case. @jeffmcaffer has a lot of the history here and can weigh in.

**Comment by RichardLitt** [comment]
Got it. This can be closed if that is going to continue to be the case. 

What other projects are referring to? I know of Libraries.io, which I think is the leader in this space. I'm not sure if Fossa keeps dep trees. Otherwise, I'm curious what other work has been done here.

**Comment by fossygirl** [comment]
@RichardLitt I'd say the list here is a good one of projects in this space: https://compliance.linuxfoundation.org/developers/process/ and yes, FOSSA as well is also in this space. Hope that helps!

**Comment by RichardLitt** [comment]
Thank you, @fossygirl! 

Closing this as arguably unactionable. @nellshamrell feel free to reopen it if you're interested in this down the road!
