### ISSUE TITLE
Design Proposal for Multi-Version Curation in ClearlyDefined

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/service#809]
Discussion is taking place on this Google doc, please comment on it.

https://docs.google.com/document/d/1TEZViX_aF2cr4pVz1SH82b287EuroU4QvtuGRc-t6X4/edit#heading=h.jjyn2b6zap3k

**Comment by disulliv** [comment]
Just wanted to share some links to demos of the work here:
- [Demo video](https://drive.google.com/file/d/19qR_iKWe89gurLmyZgf-3e9cIhJb1eyd/view?usp=sharing) by @MichaelTsengLZ 
- [Multi-version curation PR in Curated-Data-Dev](https://github.com/clearlydefined/curated-data-dev/pull/1089)
- [Auto-curated PR](https://github.com/clearlydefined/curated-data-dev/pull/1087)

**Comment by MichaelTsengLZ** [comment]
Some other bug fix PRs: https://github.com/clearlydefined/service/pull/816
