### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#812]
On this one -  https://clearlydefined.io/definitions/pypi/pypi/-/py-rouge/1.1 - the setup.py has license info but somehow the scanners missed it?  These were all run: clearlydefined/1.3.1, licensee/9.13.0, scancode/3.2.2.

![image](https://user-images.githubusercontent.com/17935946/110997621-851ff680-8332-11eb-9def-fc37ab97c317.png)

Link to setup.py: https://clearlydefined.io/file/81cbfcfdc6f8c78ea2a1129643828585b6cf8f99e6dc08d5d738472424a250aa
![image](https://user-images.githubusercontent.com/17935946/110997692-a08b0180-8332-11eb-9999-53d75789412e.png)

**Comment by nellshamrell** [comment]
Ran this locally and this is still an issue.

**Comment by pombredanne** [comment]
> Ran this locally and this is still an issue.

IMHO you ought to upgrade ScanCode.

**Comment by nellshamrell** [comment]
@pombredanne agreed, will do that ASAP

**Comment by qtomlinson** [comment]
After the ScanCode upgrade, the Discovered license shows up correctly as: Apache-2.0 (screenshot below)
![image](https://user-images.githubusercontent.com/92891533/153691215-82311f59-3ab6-4e97-9eef-595b71ea30e4.png)

**Comment by nellshamrell** [comment]
@qtomlinson Awesome! Closing this issue.
