### ISSUE TITLE
Design proposal to automatically add curation pull requests based on the previously merged curations

### ISSUE THREAD

**Issue by MichaelTsengLZ** [clearlydefined/service#818]
Discussion is taking place on this Google doc, please comment on it. Thank you!

https://docs.google.com/document/d/1MNzQ0h_qZVFNuEow7iHzi2APOmFuCzMSbEwcV5NGWjM/edit

**Comment by nellshamrell** [comment]
I believe the discussion on this concluded some time ago. Closing.
