### ISSUE TITLE
Proposal - Add maven.google.com as a Maven package source

### ISSUE THREAD

**Issue by srmorin** [clearlydefined/service#819]
The ClearlyDefined/curated-data GitHub repository is extremely valuable central repository of licensing terms for OSS packages.   Microsoft has automated tooling that identifies the license terms for OSS components it uses in its products and services.  The tooling is vital is helping Microsoft product teams to identify and comply with various license terms and to provide attribution to authors as appropriate.

Microsoft depends on packages that are published in maven.google.com for which the curated-data database has no licensing terms.  Microsoft builds many different products, services for the Android ecosystem, and spends significant effort to manually check license terms and providing proper attribution.   Microsoft is proposing to build automation tooling to collect licensing terms of packages hosted on maven.google.com for submissions to the ClearlyDefined/curated-data database for everyone to use.

MS is interested in doing this work in an upcoming sprint in the new few weeks.

**Comment by nellshamrell** [comment]
Summary:

Proposal is to add maven.google.com as a Maven package source (currently we use mavencentral and sourcearchive as sources for Maven components).

**Comment by nellshamrell** [comment]
A few notes:
* https://maven.google.com/web/index.html
* Looks like maven.google.com is a source for a relatively small number of components - all directly related to Android

**Comment by srmorin** [comment]
I put together a list of criteria together that ClearlyDefined may wish to use when considering adding other repositories in the future.  Here is the proposal:

**Introduction**:

Corporate Governance is taken very seriously at Microsoft.  As products are developed, we keep track of our open-source usage by identifying all the packages and transitive dependencies used to build that product.   We do this to ensure compliance with each package’s licensing terms, provide proper attribution to authors as required, and to identify and remediate all known security vulnerabilities in the versions we ship.  

Corporate Governance at Microsoft is mostly automated.  Our tooling can identify the open-source packages used in a product, and open work items when there is an issue identified with license terms for a particular component or a security vulnerability that needs to be remediated.   Microsoft utilizes the ClearlyDefined database as the primary source for its Corporate Governance toolingn, and we actively contribute information back when we start using a new version of a package that is not yet in the database.  

Our team distributes software for the Android platform and relies on hundreds of open-source packages from the Maven Package Manager.  Most packages used by Maven come from the Maven Central repository, but packages authored by Google come from an alternate source.  Instead, these Android packages come from maven.google.com.  ClearlyDefined currently curates data only from the primary repository for each package manager it serves.  As a result, the licensing information for about 100 Android packages are not available in the ClearlyDefined database.  This means that our team needs to either curate this information manually or build our own tooling.

Our team proposes to contribute new automation to ClearlyDefined to curate and harvest license data from maven.google.com.  We want to do this so that other Android developers can benefit from this work.  ClearlyDefined imagines that this will not be the last time they are asked to curate data from an alternate package source.   As a result, ClearlyDefined would like to identify the criteria that makes the repository a believable source of truth. 

This is a stab at doing that.  

Some Criteria to consider:

**Discoverability** – how are the packages for this language discovered?  Is the repository searched by the build tooling without the user having to customize their client?  

**Primary Source** – is this the primary repository that the package is published to?  Or is this repository a mirror of an existing repository? We should always harvest from primary sources.

**Reputability** – is this repository operated by a reputable organization? What is the purpose behind running this repository?  Is there an identifiable team that can be reached in the event of any issues?

**Security** – how secure is the repository?  Is there a team that is available to handle issues in a timely manner when they arise?  How fast do they respond to issues, such as when a security vulnerability is planted as a backdoor in a package?

**Automation** – does the repository support an API to support pulling of information?  If not, is the package index organized in a schematized format that can programmatically queried using the package name and version and queried using HTTP(s).   When using HTTP to mine data, ClearlyDefined should check for the existence of robots.txt or robot headers that indicate such mining is unacceptable.  How much effort is it to automate the process

**Relationship** – reach out to the organization that maintains the repository to indicate that ClearlyDefined wishes to harvest data from their repository, with an explanation on how harvesting is done, what the data is used for and how much additional traffic this could result in.  Identify/Resolve any concerns and provide a contact from ClearlyDefined in the event they need to support in case of an issue.

**Comment by nellshamrell** [comment]
Discussed this in this morning's community meeting and it looks good! The next step is getting the criteria into documentation. https://docs.clearlydefined.io/contributing-code is a possiblity.

**Comment by nellshamrell** [comment]
Pull request for the documentation is [here](https://github.com/clearlydefined/clearlydefined/pull/141)

**Comment by nellshamrell** [comment]
Closing because this was completed.
