### ISSUE TITLE
Need to determine what the top 1k of maven is

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#84]
We have a goal to harvest and curate the top 1k of maven packages for the OSLS announcement is. We need to figure out what this actually means.

**Comment by pombredanne** [comment]
@jeffmcaffer I have attached a CSV (with a  .txt extension) that contains 1500 of the more popular Maven jars (with when available their git repo), more or less sorted by popularity which is not a well defined thing.
[mvn1.5k.txt](https://github.com/clearlydefined/service/files/1757448/mvn1.5k.txt)

**Comment by fossygirl** [comment]
Closing, we determined this with @pombredanne's help and have done the scanning.

**Comment by fossygirl** [comment]
@pombredanne Can you enumerate a list like this for the top 10,000 maven packages for @geneh to use?

**Comment by jeffmcaffer** [comment]
More generally, can you detail the process by which you get this information so we can do it without bothering you? (and we'd like to write code for this so it can be done automatically on a periodic basis)

**Comment by fossygirl** [comment]
Per @pombredanne from Discord today: "re the Maven top 1500. That was a bit of an art more than a science and I used as a proxy mostly the stars on a corresponding source repo. There is no comprehensive Maven download stats, but let me see if I could get that from buddies @ Maven"

**Comment by fossygirl** [comment]
@pombredanne We'd still love this information from you whenever you get a chance. Since I know you've been busy, all the more reason we'd love for you to teach us to do this ourselves so we don't have to bother you again.

**Comment by jeffmcaffer** [comment]
closing. Put in some feelers to Sonatype and otherwise will just let this grow organically
