### ISSUE TITLE
Investigate Partially Harvested components

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/service#841]
https://clearlydefined.io/definitions/maven/mavengoogle/androidx.fragment/fragment/1.1.0
https://clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0
https://clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0
https://clearlydefined.io/definitions/maven/mavengoogle/com.google.android.play/core/1.7.3
https://clearlydefined.io/definitions/maven/mavengoogle/com.google.firebase/firebase-config/17.0.0
 
Are all showing as partially harvested. It's not clear why.

**Comment by nellshamrell** [comment]
Took a closer look at the cdcrawlerdev-normal queue.

Decided to try clearing the queue, then requeing up a harvest of https://dev.clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0

Interestingly, the component then harvested successfully.

**Comment by nellshamrell** [comment]
Tried the same with https://dev.clearlydefined.io/definitions/maven/mavengoogle/androidx.fragment/fragment/1.1.0 and, interestingly, the harvest also completed successfully with all tools.

I wonder if they are getting stuck in the queue somehow?

**Comment by nellshamrell** [comment]
I'm wondering if there is a way we can speed up processing of messages in the queue.

**Comment by nellshamrell** [comment]
Update to this - I believe we can at least speed up the queue by adding some more instances of the Crawler in Azure. I've requested access to the Azure subscription that contains the currently deployed instances of the Crawler and will add a few more and see if that increases the queue consumption rate.

**Comment by nellshamrell** [comment]
I initiated another harvest of https://clearlydefined.io/definitions/maven/mavengoogle/androidx.fragment/fragment/1.1.0 through [the API docs page](https://api.clearlydefined.io/api-docs/#/harvest/post_harvest) and watched the log for errors. It looks like there were indeed errors when trying to harvest this component (it's very interesting that we appear to be receiving these errors in production, but not in our Azure development environment or locally)

**Comment by pnibakuze-ms** [comment]
@nellshamrell : are you able to share the errors related with harvesting the above component? Please let me if I can help with the troubleshooting. I am curious to see if the issue is related specifically to mavengoogle provider.

**Comment by nellshamrell** [comment]
Turning my attention back to this. Interestingly, this component is showing as complete harvested:

* https://clearlydefined.io/definitions/maven/mavengoogle/androidx.fragment/fragment/1.1.0

While these are still showing as partially harvested:
* https://clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0
* https://clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0
* https://clearlydefined.io/definitions/maven/mavengoogle/com.google.android.play/core/1.7.3
* https://clearlydefined.io/definitions/maven/mavengoogle/com.google.firebase/firebase-config/17.0.0

I still suspect this is an infrastructure issue, rather than a code issue. Investigating further.

**Comment by nellshamrell** [comment]
I queued up a harvest (through the [api docs page](https://api.clearlydefined.io/api-docs/#/harvest/post_harvest) of [this component](https://clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0) and was able to identify the error in Azure Application Insights:

![image](https://user-images.githubusercontent.com/813007/119416097-c07e6000-bca7-11eb-9ae2-c2ce43fc106d.png)

Digging into the exception:

![image](https://user-images.githubusercontent.com/813007/119416127-d724b700-bca7-11eb-86b6-4d180000c4b6.png)

This is the call stack:

```
SyntaxError:
   at parse (at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19)at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19): /opt/service/node_modules/body-parser/lib/types/json.jsat parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19): 89)

   at <no_method> (at /opt/service/node_modules/body-parser/lib/read.js:121:18at /opt/service/node_modules/body-parser/lib/read.js:121:18: /opt/service/node_modules/body-parser/lib/read.jsat /opt/service/node_modules/body-parser/lib/read.js:121:18: 121)

   at invokeCallback (at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16)at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16): /opt/service/node_modules/raw-body/index.jsat invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16): 224)

   at done (at done (/opt/service/node_modules/raw-body/index.js:213:7)at done (/opt/service/node_modules/raw-body/index.js:213:7): /opt/service/node_modules/raw-body/index.jsat done (/opt/service/node_modules/raw-body/index.js:213:7): 213)

   at IncomingMessage.onEnd (at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7)at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7): /opt/service/node_modules/raw-body/index.jsat IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7): 273)

   at IncomingMessage.clsBind (at IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17)at IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17): /opt/service/node_modules/cls-hooked/context.jsat IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17): 172)

   at IncomingMessage.emit (at IncomingMessage.emit (events.js:314:20)at IncomingMessage.emit (events.js:314:20): events.jsat IncomingMessage.emit (events.js:314:20): 314)

   at IncomingMessage.emitted (at IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21)at IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21): /opt/service/node_modules/emitter-listener/listener.jsat IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21): 134)

   at endReadableNT (at endReadableNT (_stream_readable.js:1241:12)at endReadableNT (_stream_readable.js:1241:12): _stream_readable.jsat endReadableNT (_stream_readable.js:1241:12): 1241)
```

This is odd, as I believe harvesting this components works in the local dev environment and in our Azure dev environment. Confirming...

**Comment by nellshamrell** [comment]
Random thought - I wonder if it is related to the version of the body-parser npm package that is used in prod...

**Comment by nellshamrell** [comment]
Update - harvesting `/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0` worked fine locally.

It also looks like it harvested fine [in the Azure dev environment](https://dev.clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0)

Checking on the version of the body-parser gem used in local dev, Azure dev, and prod. I wonder if it's different.

**Comment by nellshamrell** [comment]
We use body-parser 1.19.0 in the local dev environment for the crawler.

However, in the service (where I believe this error is being generated, it's showing up in the clearlydefined-api-prod instance of Application insights) , here is how we list the body-parser dependency:

**package.json**
```
 "body-parser": "~1.18.2",
```

I wonder if that might be the source of the error. 

When I run it and examine the package-lock.json in the

**Comment by nellshamrell** [comment]
According to the error message, it's happening at `body-parser/lib/types/json.js`, line 89.

Looking at the source code for body parser, [here is that line of code](body-parser/lib/types/json.js:89:19)at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89)

```javascript
    try {
      debug('parse json')
      return JSON.parse(body, reviver)
    } catch (e) {
      throw normalizeJsonSyntaxError(e, {
        message: e.message,
        stack: e.stack
      })
    }
```

This is the code for version 1.19.0 of body-parser, so it seems like the error is being generated from version 1.19.0 of the body-parser npm package.

**Comment by nellshamrell** [comment]
I also confirmed that both the production environment and the Azure dev environment use the same versions of the scanning tools:

* clearlydefined/1.5.0
* licensee/9.13.0
* scancode/3.2.2

This is quite puzzling...

**Comment by nellshamrell** [comment]
# Summary So Far

## The Problem

The `maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0` component shows as "partially harvested" in the [production instance of ClearlyDefined](https://clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0).

However, it shows as "harvested" in the [ClearlyDefined Azure Dev Environment](https://dev.clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0). It also shows as "harvested" when running the ClearlyDefined services locally.

### What does "Harvested" and "Partially Harvested" mean?

Clearly Defined uses three tools for scanning components for licenses:
* clearlydefined
* licensee
* scancode

When a component is **Partially Harvested**, that means that only one scanning tool ran successfully.

If we look at the [production definition for maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0](https://clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0), we see that only one tool `clearlydefined/1.5.0` successfully scanned the component.

However, if we look at the [dev environment definition for maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0](https://dev.clearlydefined.io/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0), we see that all three tools successfully scanned the component.

* clearlydefined/1.5.0
* licensee/9.13.0
* scancode/3.2.2

There is something inconsistent between the production and Azure dev environment.

## Initial Troubleshooting

There is an error that shows up in our Application Insights set up for the production ClearlyDefined service. The error occurs when trying to hit the /harvest endpoint for the API:

```
SvcRequestFailure:/harvest
```

With this call stack:

```
SyntaxError:
   at parse (at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19)at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19): /opt/service/node_modules/body-parser/lib/types/json.jsat parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19): 89)

   at <no_method> (at /opt/service/node_modules/body-parser/lib/read.js:121:18at /opt/service/node_modules/body-parser/lib/read.js:121:18: /opt/service/node_modules/body-parser/lib/read.jsat /opt/service/node_modules/body-parser/lib/read.js:121:18: 121)

   at invokeCallback (at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16)at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16): /opt/service/node_modules/raw-body/index.jsat invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16): 224)

   at done (at done (/opt/service/node_modules/raw-body/index.js:213:7)at done (/opt/service/node_modules/raw-body/index.js:213:7): /opt/service/node_modules/raw-body/index.jsat done (/opt/service/node_modules/raw-body/index.js:213:7): 213)

   at IncomingMessage.onEnd (at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7)at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7): /opt/service/node_modules/raw-body/index.jsat IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7): 273)

   at IncomingMessage.clsBind (at IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17)at IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17): /opt/service/node_modules/cls-hooked/context.jsat IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17): 172)

   at IncomingMessage.emit (at IncomingMessage.emit (events.js:314:20)at IncomingMessage.emit (events.js:314:20): events.jsat IncomingMessage.emit (events.js:314:20): 314)

   at IncomingMessage.emitted (at IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21)at IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21): /opt/service/node_modules/emitter-listener/listener.jsat IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21): 134)

   at endReadableNT (at endReadableNT (_stream_readable.js:1241:12)at endReadableNT (_stream_readable.js:1241:12): _stream_readable.jsat endReadableNT (_stream_readable.js:1241:12): 1241)
```

This appears to originate in the body-parser npm package, which is a dependency of the ClearlyDefined service.

### body-parser package

I wondered if we might be running a different version of `body-parser` in production than we were running in the dev environment.

Looking at the [package-lock.json] file for the ClearlyDefined service, we use two version of `body-parser` in the ClearlyDefined service:
* [1.18.2](https://github.com/clearlydefined/service/blob/1d735b3bb693af4c2a982873a8079d5dd721d575/package-lock.json#L875), which is defined as a dependency in the service's [package.json](https://github.com/clearlydefined/service/blob/1d735b3bb693af4c2a982873a8079d5dd721d575/package.json#L24)
* [1.18.3](https://github.com/clearlydefined/service/blob/1d735b3bb693af4c2a982873a8079d5dd721d575/package-lock.json#L2158) (this is a dependency of the express dependency)

I confirmed that the same versions of `body-parser` are present in the package-lock.json file used by the local dev environment. It should also be the same for the Azure dev environment, since that is generated using the same package-lock.json file as the production environment. 

So it doesn't seem to be a difference in `body-parser` versions.

## Infrastructure Set Up

The production and development environments run similar, though not identical, infrastructure.

The main service is run as a Docker container, I believe both the production and Azure dev environment Docker images are created using [this Dockerfile](https://github.com/clearlydefined/service/blob/master/Dockerfile). (The local development environment uses a [different Dockerfile](https://github.com/clearlydefined/service/blob/master/DevDockerfile).

## Scanning Tool versions

I wondered if we might be using different versions of licensee and scancode in the production and development environments.

* Looking at a recent [successful harvest of a component in production](https://clearlydefined.io/definitions/maven/mavengoogle/android.arch.navigation/navigation-common/1.0.0) and comparing it to a [successful harvest of the same component in dev](https://dev.clearlydefined.io/definitions/maven/mavengoogle/android.arch.navigation/navigation-common/1.0.0), they appear to be using the same versions of clearlydefined, licensee, and scancode.

* clearlydefined/1.5.0
* licensee/9.13.0
* scancode/3.2.2

So it does not appear to be an issue of using different versions of those tools.

**Comment by nellshamrell** [comment]
Interesting thing I just discovered:

If I attempt a harvest through the production API, I get this error:

```
curl -X POST "https://api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]"

{"error":{"code":"400","message":"An error has occurred","innererror":{}}}
```

If I run it through the Azure dev environment API, I get this error:

```
curl -X POST "https://dev-api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]"
{"error":{"code":"400","message":"An error has occurred","innererror":{"expose":true,"statusCode":400,"status":400,"body":"[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]","type":"entity.parse.failed","name":"SyntaxError","message":"Unexpected token ] in JSON at position 116","stack":"SyntaxError: Unexpected token ] in JSON at position 116\n    at JSON.parse (<anonymous>)\n    at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19)\n    at /opt/service/node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16)\n    at done (/opt/service/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7)\n    at IncomingMessage.clsBind (/opt/service/node_modules/cls-hooked/context.js:172:17)\n    at IncomingMessage.emit (events.js:314:20)\n    at IncomingMessage.emitted (/opt/service/node_modules/emitter-listener/listener.js:134:21)\n    at endReadableNT (_stream_readable.js:1241:12)"}}}
```

Which is the same error we see in Application insights for the production service.

**Comment by nellshamrell** [comment]
I also see this error in my local dev environment:

```
curl -X POST "http://localhost:4000/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]"
{"error":{"code":"400","message":"An error has occurred","innererror":{"expose":true,"statusCode":400,"status":400,"body":"[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]","type":"entity.parse.failed","name":"SyntaxError","message":"Unexpected token ] in JSON at position 116","stack":"SyntaxError: Unexpected token ] in JSON at position 116\n    at JSON.parse (<anonymous>)\n    at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19)\n    at /opt/service/node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16)\n    at done (/opt/service/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7)\n    at IncomingMessage.emit (events.js:314:20)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}}
```

So...this error may be a red herring.

**Comment by nellshamrell** [comment]
Something else interesting:

In my local dev environment, if I queue up a harvest by visiting the definitions UI page for those component coordinates:

http://localhost:3000/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0

It harvests the component using all three tools.

* clearlydefined/1.5.0
* licensee/9.13.0
* scancode/3.2.2

Yet when I request a harvest of it through the API in my local dev environment, I receive that error.

```
 curl -X POST "http://localhost:4000/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]"

{"error":{"code":"400","message":"An error has occurred","innererror":{"expose":true,"statusCode":400,"status":400,"body":"[ { \"tool\": \"package\", \"coordinates\": \"/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\" },]","type":"entity.parse.failed","name":"SyntaxError","message":"Unexpected token ] in JSON at position 116","stack":"SyntaxError: Unexpected token ] in JSON at position 116\n    at JSON.parse (<anonymous>)\n    at parse (/opt/service/node_modules/body-parser/lib/types/json.js:89:19)\n    at /opt/service/node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/opt/service/node_modules/raw-body/index.js:224:16)\n    at done (/opt/service/node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/opt/service/node_modules/raw-body/index.js:273:7)\n    at IncomingMessage.emit (events.js:314:20)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"}}}
```

And the harvest does not appear to be executed.

What's also curious is once I visit the definition page in the UI at http://localhost:3000/definitions/maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0, a harvest is successfully harvested.

**Comment by nellshamrell** [comment]
Update:

Please disregard the past three comments, there was an error in the JSON included in my API call.

This curl command:

```
curl -X POST "https://api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[{\"tool\":\"package\",\"coordinates\":\"maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\"}]"
```

and this one

```
curl -X POST "https://api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[{\"tool\":\"package\",\"coordinates\":\"maven/mavengoogle/androidx.asynclayoutinflater/asynclayoutinflater/1.0.0\"}]"
```

Appear to work fine.

**Comment by nellshamrell** [comment]
I have a new theory:

I've managed to generate some instances in both the dev environment and the production environment where only some of the scanning tools run successfully. When that happens, I'm noticing ENOMEM errors in the crawler logs. This may be related. It's possible we could fix this through increasing the resources in the crawler instance.

I have to sign off for the day soon, but will continue troubleshooting tomorrow.

**Comment by nellshamrell** [comment]
Just tried to re-harvest [maven/mavengoogle/androidx.annotation/annotation/1.0.0](https://clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0) in production (which originally only showed that clearlydefined had successfully run on it, but after several re-tries started showing the licensee had successfully run yesterday).

I used this API call:

```bash
curl -X POST "https://api.clearlydefined.io/harvest" -H "accept: */*" -H "Content-Type: application/json" -d "[{\"tool\":\"package\",\"coordinates\":\"maven/mavengoogle/androidx.annotation/annotation/1.0.0\"}]"
```

Several errors were generated in the crawler when it tried to run the harvest tools on it. Here are several screenshots.

![image](https://user-images.githubusercontent.com/813007/120044842-7f49c100-bfc3-11eb-8a3f-56ff76a6d12d.png)

![image](https://user-images.githubusercontent.com/813007/120044891-9be5f900-bfc3-11eb-88c1-b0d8410275cb.png)

![image](https://user-images.githubusercontent.com/813007/120044934-b4561380-bfc3-11eb-9e00-42ad9301ff2e.png)

The ones that are standing out to me are

```
Error scancode@cd:/sourcearchive/mavengoogle/androidx.annotation/annotation/1.0.0 spawn ENOMEM

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:553:9)
    at execFile (child_process.js:237:17)
    at child_process.js:172:29
    at ScanCodeProcessor._runScancode (/opt/service/providers/process/scancode.js:52:13)
    at ScanCodeProcessor.handle (/opt/service/providers/process/scancode.js:33:16)
    at async Crawler._process (/opt/service/ghcrawler/lib/crawler.js:503:20)
    at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}

Error licensee@cd:/sourcearchive/mavengoogle/androidx.annotation/annotation/1.0.0 spawn ENOMEM
```

It seems like we are running out of memory when running scancode and licensee on this component with the production crawler.

**Comment by ariel11** [comment]
Thanks for looking into this!  I think it would save a lot of work to get all the scanner running...  Thanks!

**Comment by nellshamrell** [comment]
I think we may be able to solve this by not storing the temporary results of the scan in the container (which we currently do), but rather store them in a drive that is mounted to the crawler containers. Going to experiment with this approach this week.

**Comment by nellshamrell** [comment]
Update:

I've deployed a change to the crawler's code which should improve this situation, but requires some infrastructure changes that need to be coordinated in Azure, AWS, and Google Cloud. I've proven out the Azure change in a development environment and am working on getting those infra changes done in our production environment. 

I've made contact with people at AWS who may be able to help and am searching for someone in Google Cloud who may be able to help as well.

The good news is I think the majority of our crawlers live in Azure, so the chance of hitting one with this change (which allows for bigger harvests without running out of memory) should be high.

I will update here when I get the changes made in Azure.

**Comment by nellshamrell** [comment]
The Azure crawlers were upgraded yesterday. Re-trying some of the partially harvested components.

**Comment by nellshamrell** [comment]
I have some good news on this - it appears to be working much better!

I re-ran the harvest for https://clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0 

It previously only showed the clearlydefined and licensee ran successfully on it, however it's now showing scancode running successfully as well.

I'm working on getting a list of some other partially harvested components to re-harvest.

**Comment by nellshamrell** [comment]
Re-ran https://clearlydefined.io/definitions/maven/mavengoogle/androidx.annotation/annotation/1.0.0 and all the scanning tools ran successfully!

**Comment by nellshamrell** [comment]
This is fixed! (Confirmed by re-running incomplete harvests listed in #846).
