### ISSUE TITLE
The declared license for crate/cratesio/-/slog/2.7.0 is not the same as in the Cargo.toml file 

### ISSUE THREAD

**Issue by MichaelTsengLZ** [clearlydefined/service#847]
For [crate/cratesio/-/slog/2.7.0](https://clearlydefined.io/definitions/crate/cratesio/-/slog/2.7.0), the declared license is shown as `Apache-2.0 AND MIT AND MPL-2.0` in the first screenshot. However, the Cargo.toml file show `MPL-2.0 OR MIT OR Apache-2.0` [here](https://github.com/slog-rs/slog/blob/master/Cargo.toml#L8) and [here](https://crates.io/crates/slog). 

![image](https://user-images.githubusercontent.com/20408623/120535753-35cced80-c398-11eb-9780-268f4b122e0f.png)
![image](https://user-images.githubusercontent.com/20408623/120535974-74fb3e80-c398-11eb-82d1-a5a7dee5b65f.png)

**Comment by johnbatty** [comment]
This issue does not appear to be specific to `slog` - it appears that the declared license may be wrong for all Rust crates with multiple licenses.

I checked 3 crates from the "top 10 downloads" on `crates.io`, and they all show the same issue - `Cargo.toml` specifies `MIT OR Apache-2.0` (very typical for Rust crates), but `clearlydefined` declares `MIT AND Apache-2.0`:
* `rand`: https://clearlydefined.io/?type=crate&sort=releaseDate&sortDesc=true&name=rand
  * For the latest version `clearlydefined` has a different (but still wrong) declaration: `MIT OR (Apache-2.0 AND MIT)` 
* `libc`: https://clearlydefined.io/?type=crate&sortDesc=true&sort=releaseDate&name=libc
* `quote`: https://clearlydefined.io/?type=crate&sortDesc=true&sort=releaseDate&name=libc

**Comment by johnbatty** [comment]
I have raised a separate issue for the fact that license declaration is broken for most Rust crates with license choices: https://github.com/clearlydefined/service/issues/856

**Comment by nellshamrell** [comment]
This appears to have been fixed by the PR that fixed #856. Closing.
