### ISSUE TITLE
Validate schemas for Contributions

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/service#86]
per conversation with @mynameistechno we need to validate schemas for all the posts. In particular, we need to validate the requests to create contributions/PRs. need to fail this before creating the PR if possible.

**Comment by jeffmcaffer** [comment]
@Teju-Manchenella has started working on this. Specifically updating the `curation` schema and hooking in the error reporting appropriately.

**Comment by Teju-Manchenella** [comment]
PR #169
