### ISSUE TITLE
PyPi components should treat - and _ as the same

### ISSUE THREAD

**Issue by disulliv** [clearlydefined/service#860]
Information found here: https://github.com/package-url/purl-spec/blame/180c46d266c45aa2bd81a2038af3f78e87bb4a25/README.rst#L679

For example, these 2 links resolve to the same thing:
https://pypi.org/project/backports.ssl_match_hostname/
https://pypi.org/project/Backports.ssl-match-hostname/

However, in Clearly Defined, these components are not equivalent:
https://clearlydefined.io/definitions/pypi/pypi/-/backports.ssl_match_hostname/3.7.0.1
https://clearlydefined.io/definitions/pypi/pypi/-/backports.ssl-match-hostname/3.7.0.1

One way to go about this is for all PyPi components, automatically resolve the component name as all lowercase and convert all _ to -'s to standardize.

**Comment by nellshamrell** [comment]
This would be a good starter issue.

One idea for implementation:

Whenever a request comes in for a pypi definition (it would come into the getDefinition route](https://github.com/clearlydefined/service/blob/e2478a1626ebe6cdc13cedefd9afcf48b61b4af9/routes/definitions.js#L17) and the name of the component has an underscore (_), automatically convert the underscore into a hyphen (-).

**Comment by qtomlinson** [comment]
https://www.python.org/dev/peps/pep-0503/#normalized-names mentioned that "." should also be treated same as -, and _.

**Comment by nellshamrell** [comment]
This was fixed with #893
