### ISSUE TITLE
Error behavior of API

### ISSUE THREAD

**Issue by mbtools** [clearlydefined/service#870]
Hi CD team,

I'm trying to build a service for displaying the CD license score as a badge (https://shields.io/). This will use the definitions API (https://api.clearlydefined.io/definitions/). The implementation works fine if the definition exists (HTTP 200). However, when using parameters that point to non-existing definitions, the error behavior does not seems to be logical. 

`GET /definitions/{type}/{provider}/{namespace}/{name}/{revision}`:

- Invalid/unknown revision: HTTP 200 response with a score of 0
- Invalid/unknown package: HTTP 200 response with a score of 0
- Invalid/unknown namespace: HTTP 200 response with a score of 0
- Invalid/unknown provider: HTTP 500 response, message "An error has occurred" > not a great message but acceptable
- Invalid/unknown type: HTTP 500 response, message "An error has occurred" > not a great message but acceptable

Why does the API not return an error in the first three cases? Wouldn't HTTP 404 "Not found" make more sense (typical for other APIs)? 

Best,
Marc

**Comment by nellshamrell** [comment]
Hi @mbtools! That sounds like an awesome project!

I was not around when the error messages were created and am unsure of the reasoning. @jeffmcaffer when you have a moment could you comment on the error message decisions here?

**Comment by waynebeaton** [comment]
It would be handy if we could get some feedback regarding what was actually specified incorrectly.

I'm trying to load up requests with as much data as I can. So, in some cases, I'm sending 1K records to the "/definitions" API. When one of the entries is bad, I get a 200 response code with a very generic error message.

e.g., with this payload (note that I'm using an example that, pending completion of Issue #871, will start working) :

````
[
  "git/github/microsoft/redie/194269b5b7010ad6f8dc4ef608c88128615031ca",
  "npm/npmjs/-/redie/0.3.0",
  "go/golang/github.com%2Fspf13/cobra/0.0.5"
]
````

I get 200 and this response:

> An error occured when trying to fetch coordinates for one of the components: data/coordinates/type should be equal to one of the allowed values, data/coordinates/provider should be equal to one of the allowed values

It would be handy to have an option that helps me programmatically identify the incorrect values so that I can extract partial answers. Filtering out IDs that are structured incorrectly is easy, but I don't know of a way to filter out based on bogus type/source (is there an API that provides a list of valid types and sources?).

I would also prefer a more explicit "not found" to a zero score.

**Comment by bduranc** [comment]
Jeff and Nell will probably be able to add more helpful context here.

But I believe this has been a long-standing issue and currently has to be accounted for by the end-user / data-consumer. 

Within my own organization, our internal tools evaluate the definition's state by checking individual elements like the score values and what tools are present. We also pass the coordinates ahead of time through a validator to ensure they are correct before making the request. Needless to say, any improvement to the API that will better communicate errors would be a welcome one IMHO.

The API will also still try and queue up a component that isn't already harvested as long as the coordinates are valid, which has proven to be a useful feature if you don't want to make two separate API requests to "check if exists" + harvest.  Still, even in this case a 404 would probably still be an appropriate status code to return in the event a definition doesn't already exist.

**Comment by mbtools** [comment]
Here are examples for the cases I mentioned:

- Valid request
https://api.clearlydefined.io/definitions/npm/npmjs/-/jquery/3.4.1

+1 for returning 404 on all of the following:

- Invalid/unknown revision: HTTP 200 response with a score of 0
https://api.clearlydefined.io/definitions/npm/npmjs/-/jquery/3.99.99
- Invalid/unknown package: HTTP 200 response with a score of 0
https://api.clearlydefined.io/definitions/npm/npmjs/-/jquery-xyz/3.4.1
- Invalid/unknown namespace: HTTP 200 response with a score of 0
https://api.clearlydefined.io/definitions/npm/npmjs/test/jquery/3.4.1
- Invalid/unknown provider: HTTP 500 response, message "An error has occurred" > not a great message but acceptable
https://api.clearlydefined.io/definitions/npm/test/-/jquery/3.4.1
- Invalid/unknown type: HTTP 500 response, message "An error has occurred" > not a great message but acceptable
https://api.clearlydefined.io/definitions/test/npmjs/-/jquery/3.4.1

PS: Triggering the harvest on "not found" sounds to me like potential performance problems. Also, as an API user, I certainly don't expect anything to change on the server-side if I do a GET.

**Comment by mbtools** [comment]
Understood. I'm now using the `described:files` count to determine if the definition is one of the cases above (no files) or not (i.e. a legit score of 0). 

Unless you want to keep the discussion going, we can close this.
