### ISSUE TITLE
Add support for Gradle Plugin Repository

### ISSUE THREAD

**Issue by BrianGGreen** [clearlydefined/service#882]
Hi Folks, this is a request for support for the repo: https://plugins.gradle.org/m2/ from [Gradle](https://gradle.org/)

Discoverability – how are the packages for this language discovered? Is the repository searched by the build tooling without the user having to customize their client?

- Packages are formatted and used in the same manner as java's maven repositories.  These plugins are used for Android on my team.  The gradle tools allow us to use the packages on the site without [any extra effort](https://docs.gradle.org/current/userguide/plugins.html)

Primary Source – is this the primary repository that the package is published to? Or is this repository a mirror of an existing repository? We should always harvest from primary sources.

- Gradle has some overlap in packages with MavenCentral, but it is the primary source for any package that is Gradle specific such as the Kotlinter

Reputability – is this repository operated by a reputable organization? What is the purpose behind running this repository? Is there an identifiable team that can be reached in the event of any issues?

- The Gradle organization hosts both the [free tooling](https://gradle.org/) and the [enterprise solution](https://gradle.com/).  The repository supports their organization.  Gradle has [forums ](https://discuss.gradle.org/) for gradle related issues

Security – how secure is the repository? Is there a team that is available to handle issues in a timely manner when they arise? How fast do they respond to issues, such as when a security vulnerability is planted as a backdoor in a package?

- I don't have much info here, but Gradle is a reputable organization in the [top 20 Open Source projects
](https://techcrunch.com/2017/04/07/tracking-the-explosive-growth-of-open-source-software/)

Automation – does the repository support an API to support pulling of information? If not, is the package index organized in a schematized format that can programmatically queried using the package name and version and queried using HTTP(s). When using HTTP to mine data, ClearlyDefined should check for the existence of robots.txt or robot headers that indicate such mining is unacceptable. How much effort is it to automate the process?

- The gradle plugin site is a m2 site similar to the MavenCentral in formatting and should not be too hard to pick up(I think).  This specific part isn't my strong suit, which is why I am opening a request here instead of doing it myself and submitting a PR.  

Relationship – reach out to the organization that maintains the repository to indicate that ClearlyDefined wishes to harvest data from their repository, with an explanation on how harvesting is done, what the data is used for and how much additional traffic this could result in. Identify/Resolve any concerns and provide a contact from ClearlyDefined in the event they need to support in case of an issue.

- If we choose to move forward here, we can contact on the[ forums](https://discuss.gradle.org/) or on their [contacts](https://gradle.org/contact/)

**Comment by nellshamrell** [comment]
For examples of how to implement this, see these two pull requests:

* https://github.com/clearlydefined/service/pull/829
* https://github.com/clearlydefined/crawler/pull/424

**Comment by qtomlinson** [comment]
I am new to Gradle plugins.  From what I have read so far, the Gradle plugins repository layout is similar to a maven repository.  Harvesting plugins should be similar to harvesting maven artifacts for the most part.  There are however the additional features in Gradle plug in that warrants consideration:

1. Newer versions of Gradle plugins contain [Gradle Module Metadata](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html).  Is this particular metadata to be included in our harvest?

2. To specify a particular Gradle plugin, there are two ways:
- via globally unique plugin id and version in DSL.  Internally, gradle generates a [Plugin Marker Artifact] (https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers), which contains the mapping from id/version to maven groupId/artifactId/version.
- via maven groupId/artifactId/version (legacy).  

From implementation standpoint, the translation/mapping from id/version to maven gav can be achieved in the coordinatesMapper in Service.  Crawler only needs to deal with the converted gav information.  

Currently, no restriction is imposed on maven coordinates in Service that namespace have to to be provided.  In light of this, Gradle plugin coordinates can be implemented as of type 'maven' and provider 'gradleplugin'.  For example:
for the id/version spec in 2.a:
```
{
      type: 'maven',
      provider: 'gradleplugin',
      namespace: '-',
      name: 'io.github.lognet.grpc-spring-boot'
      version: '4.5.4'
    }
```
for the corresponding gav spec in 2.b:
```
{
      type: 'maven',
      provider: 'gradleplugin',
      namespace: 'io.github.lognet',
      name: 'grpc-spring-boot-starter-gradle-plugin'
      version: '4.5.4'
}
```
Do coordinates and naming look reasonable?
Appreciate any feedback!

**Comment by nellshamrell** [comment]
Looks completely reasonable to me!

**Comment by qtomlinson** [comment]
hm... When looking up a gradle plugin by plugin.id + plugin.version, "Gradle will look for a Plugin Marker Artifact with the coordinates plugin.id:plugin.id.gradle.plugin:plugin.version." See https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers.  

Shall we use namespace as the place holder for plugin.id, to be consistent? The above example in 2.a becomes: 
```
  {
      type: 'maven',
      provider: 'gradleplugin',
      namespace: 'io.github.lognet.grpc-spring-boot',
      name: '-'
      version: '4.5.4'
  }
```
This is a bit different from the current practice of allowing only empty name spaces.  Any thoughts?

**Comment by nellshamrell** [comment]
@BrianGGreen This has been deployed and is now live!

Here's an example set of coordinates:

```
maven/gradleplugin/-/org.danilopianini.gradle-kotlin-qa/0.10.1
```
