### ISSUE TITLE
Error summarizing harvested file for a component revision with tool and toolVersion

### ISSUE THREAD

**Issue by qtomlinson** [clearlydefined/service#887]
Expected: No error retrieving harvested file for a component revision with tool and toolVersion
Observed: Error "summarizeService.summarize is not a function" is reported, when retrieving harvested file for a component revision with summary using https://api.clearlydefined.io/api-docs/#/harvest/get_harvest__type___provider___namespace___name___revision___tool___toolVersion_

Reproducing step:
1. curl -X GET "https://dev-api.clearlydefined.io/harvest/npm/npmjs/-/redie/0.3.0/clearlydefined/1.3.4?form=list" -H "accept: */*"
returns data
2. curl -X GET "https://dev-api.clearlydefined.io/harvest/npm/npmjs/-/redie/0.3.0/clearlydefined/1.3.4?form=summary" -H "accept: */*"
returns the following error:
```
{
  "error": {
    "code": "500",
    "message": "An error has occurred",
    "innererror": {
      "name": "TypeError",
      "message": "summarizeService.summarize is not a function",
      "stack": "TypeError: summarizeService.summarize is not a function\n    at get (/opt/service/routes/harvest.js:26:45)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /opt/service/middleware/asyncMiddleware.js:6:5"
    }
  }
}
```

**Comment by nellshamrell** [comment]
This was fixed with #888
